Shot vector property
PennyLaneAI/pennylane pull request #1168
Opened 2021-03-25 20:31 UTC by Thenerdstation

Fixes #1164

2021-03-26 15:20 UTC, josh146 requested changes
Thanks @Thenerdstation, just needs a docstring (have left one I had made earlier). Might also be worth adding this PR to the changelog. I don't think it needs its own entry, maybe just add the PR link to the existing shots refactor III

2021-03-26 15:20 UTC, josh146 commented on pennylane/_device.py
> +    def shot_vector(self):
```suggestion
    def shot_vector(self):
    """list[.ShotTuple[int, int]]: Returns the shot vector, a sparse
    representation of the shot sequence used by the device
    when evaluating QNodes.

    **Example**

    >>> dev = qml.device("default.qubit", wires=2, shots=[3, 1, 2, 2, 2, 2, 6, 1, 1, 5, 12, 10, 10])
    >>> dev.shots
    57
    >>> dev.shot_vector
    [ShotTuple(shots=3, copies=1),
     ShotTuple(shots=1, copies=1),
     ShotTuple(shots=2, copies=4),
     ShotTuple(shots=6, copies=1),
     ShotTuple(shots=1, copies=2),
     ShotTuple(shots=5, copies=1),
     ShotTuple(shots=12, copies=1),
     ShotTuple(shots=10, copies=2)]

    The sparse representation of the shot
    sequence is returned, where tuples indicate the number of times a shot
    integer is repeated.
    """
```

2021-03-26 15:20 UTC, josh146 commented on pennylane/_device.py
> +    def shot_vector(self):
I had this docstring lying around in one of my local files. I haven't tested it, but I recommend running the example code just to make sure that's what it outputs 😆

2021-03-28 15:13 UTC, josh146 commented on pennylane/_device.py
> +    """
```suggestion
        """list[.ShotTuple[int, int]]: Returns the shot vector, a sparse
        representation of the shot sequence used by the device
        when evaluating QNodes.

        **Example**

        >>> dev = qml.device("default.qubit", wires=2, shots=[3, 1, 2, 2, 2, 2, 6, 1, 1, 5, 12, 10, 10])
        >>> dev.shots
        57
        >>> dev.shot_vector
        [ShotTuple(shots=3, copies=1),
         ShotTuple(shots=1, copies=1),
         ShotTuple(shots=2, copies=4),
         ShotTuple(shots=6, copies=1),
         ShotTuple(shots=1, copies=2),
         ShotTuple(shots=5, copies=1),
         ShotTuple(shots=12, copies=1),
         ShotTuple(shots=10, copies=2)]

        The sparse representation of the shot
        sequence is returned, where tuples indicate the number of times a shot
        integer is repeated.
        """
```

2021-03-29 14:36 UTC, Thenerdstation commented
@josh146 I think you fixed your own change request so can we merge this?

2021-03-29 16:09 UTC, josh146 approved these changes

2021-03-29 16:41 UTC, merged