add out_flow_constraint function and private function, add unit tests
PennyLaneAI/pennylane pull request #1220
Opened 2021-04-15 16:10 UTC by anthayes92

For the max weighted cycle QAOA problem, the unconstrained approach requires constraints to be included in the cost Hamiltonian. An out flow constraint is introduced to the cost Hamiltonian to help ensure it's minimised by selecting edges such that each node has an out flow equal to 0 or 1. 

Add a out flow constraint function.
Add a private function to calculate quadratic terms of the constraint.

Allows a user to easily introduce constraints to cost Hamiltonian.

It relies on private functions that may be redundant when changes to `qml.Hamiltonian` are introduced

2021-04-19 21:51 UTC, trbromley requested changes
Thanks @anthayes92 :100: Looking great, mainly left comments for the docs.

Should be able to start merging in tomorrow and will clear the backlog. Great that we've got this in so quickly!

2021-04-19 21:51 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +    The out flow constraint is, for all :math:`i`:
```suggestion
    Given a subset of edges in a directed graph, the out-flow constraint imposes that at most one
    edge can leave any given node, i.e., for all :math:`i`:
```

2021-04-19 21:51 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +    The corresponding qubit Hamiltonian is:
```suggestion
    A set of edges satisfies the out-flow constraint whenever the following Hamiltonian is minimized:
```

2021-04-19 21:51 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +        \frac{1}{4}\sum_{i\in V}\left(d_{i}^{out}(d_{i}^{out} - 2)\mathbb{I}
```suggestion
        \sum_{i\in V}\left(d_{i}^{out}(d_{i}^{out} - 2)\mathbb{I}
```

2021-04-19 21:51 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +    r"""Calculates the expanded inner portion of the Hamiltonian in :func:`out_flow_constraint`.
```suggestion
    r"""Calculates the inner portion of the Hamiltonian in :func:`out_flow_constraint`.
```

2021-05-05 17:30 UTC, anthayes92 commented on pennylane/qaoa/cycle.py
> +def _inner_out_flow_constraint_hamiltonian(
I see where you're coming from! It follows the convention of the net flow contraint functions and since it's private I think it's ok

2021-05-05 17:30 UTC, anthayes92 commented on tests/test_qaoa.py
> +        assert all([op.wires == exp.wires for op, exp in zip(h.ops, expected_ops)])
addressed here: 407b469931ab7ce8377d1447f2b3eae56b55f970

2021-05-06 13:52 UTC, trbromley approved these changes
Thanks @anthayes92, approved! Although I left some quick suggestions. Also, don't forget to update the changelog!

2021-05-06 13:52 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +        graph (nx.DiGraph): the graph specifying possible edges
```suggestion
        graph (nx.DiGraph): the directed graph specifying possible edges
```

2021-05-06 13:52 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +) -> Tuple[List[float], List[qml.operation.Observable]]:
```suggestion
) -> qml.Hamiltonian:
```

2021-05-06 13:52 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +        graph (nx.DiGraph): the graph specifying possible edges
```suggestion
        graph (nx.DiGraph): the directed graph specifying possible edges
```

2021-05-06 13:52 UTC, trbromley commented on pennylane/qaoa/cycle.py
> +        observables of the inner part of the node-constraint Hamiltonian.
```suggestion
        qml.Hamiltonian: The inner part of the out-flow constraint Hamiltonian.
```

2021-05-06 13:52 UTC, trbromley commented on tests/test_qaoa.py
> +            print(str(h.ops[i]) == str(expected_op))
```suggestion
            assert str(h.ops[i]) == str(expected_op)
```

2021-05-06 13:52 UTC, trbromley commented on tests/test_qaoa.py
> +            print(str(h.ops[i]) == str(expected_op))
```suggestion
            assert str(h.ops[i]) == str(expected_op)
```

2021-05-06 15:50 UTC, merged