[unitaryHACK] Added SWAP decomposition and related tests
PennyLaneAI/pennylane pull request #1317
Opened 2021-05-14 20:40 UTC by charmerDark

**Context:**
Added SWAP decomposition and wrote tests to it

**Description of the Change:**
added the the function 
 ``` 
  @staticmethod
    def decomposition(wires): 
```
to ` pennylane/ops/qubit.py `  and tests for it at ` tests/ops/test_qubit_ops.py `

**Possible Drawbacks:**
The tests only run through some specific cases and cannot be considered very conclusive. This also seems to apply to many of the pre-existing tests too
**Related GitHub Issues:**
resolves #1304

2021-05-15 00:28 UTC, antalszava requested changes
Hi @charmerDark, thank you for submitting this PR! :slightly_smiling_face: :+1: Overall, it's starting to look great already!

There would be a couple of adjustments to make:
1. Formatting the files using `black` by running `black -l 100 pennylane/`. The `21.5b1` version of `black` is required for that, it can be installed by `pip install black --upgrade`.
2. a) Adding a one-sentence description and a link to this PR in the `.github/CHANGELOG.md` file. Other PRs could serve as an example there.
    b) Adding yourself as a contributor to the list of contributors! :slightly_smiling_face: 

> The tests only run through some specific cases and cannot be considered very conclusive. This also seems to apply to many of the pre-existing tests too

Could you elaborate on this point from the PR description?

----

On another note, no need to worry about the failing test cases for now. :slightly_smiling_face:  These are due to existing test cases that assumed that the `qml.SWAP` operation has no decomposition (we'll be [adjusting them separately](https://github.com/PennyLaneAI/pennylane/pull/1318)).

2021-05-15 03:48 UTC, charmerDark commented
> Could you elaborate on this point from the PR description?
The test written for the SWAP operation assumes that the decomposition is composed of CNOT gates. This cannot be considered a conclusive test in my opinion.

2021-05-17 07:39 UTC, charmerDark commented
@antalszava  #1313 is what I was trying to convey in the possible drawbacks section of this PR. I just couldn't articulate it that well

2021-05-17 14:27 UTC, antalszava requested changes
Hi @charmerdark, thank you for the adjustments! :slightly_smiling_face: Yes, it indeed makes sense to further consider the best way of testing, though it's okay to have that on the side for now.

As for the changes, a couple of small last steps would remain:
1. Thanks for the addition in the changelog! Could you add yourself to the [list of contributors](https://github.com/PennyLaneAI/pennylane/blame/master/.github/CHANGELOG.md#L253)?
2. Formatting the files was great, the check now passes well! :slightly_smiling_face: One thing is, that certain files are good to be left unformatted (e.g., docs, benchmark files, etc.). The command `black -l 100 pennylane/` is meant to be executed from the `pennylane` directory such that it formats the `pennylane` subdirectory where the source files are to be found (this was not specified, sorry if it caused confusion~). Could you perhaps revert the formatting commit using `git` and reformat such that only the `pennylane` subdirectory is formatted?

Let us know if you have any questions! :)

2021-05-17 14:27 UTC, antalszava commented on .github/CHANGELOG.md
> +  has decompositions over elementary gates.
(Minor suggestion)
```suggestion
  has a decomposition over elementary gates.
```

2021-05-17 15:53 UTC, charmerDark commented
Wont reverting changes now cause conflict  with the merge from the main that happened right now? I am a bit confused with the `git revert` and how to use it. Could you please help me a bit?

2021-05-17 16:06 UTC, antalszava commented
Hi @charmerDark, sure :slightly_smiling_face:

The `git revert 2ff25c789a20156fda3cebb2da92953c70365c14` command should do it, where the string after `revert` is the hash of the formatting commit, 2ff25c789a20156fda3cebb2da92953c70365c14. `git` will apply the "inverse" of the changes in that particular commit when using `git revert`, meaning that it will effectively unchange any updates coming from there. There should be no issues from later merges of `master`. :slightly_smiling_face:

2021-05-17 16:33 UTC, charmerDark commented
I made the changes after reverting the branch. However I encountered the error message 
```Updates were rejected because the tip of your current branch is behind its remote counterpart. Integrate the remote changes```
Could you help me with this too?  So sorry you had to babysit me through this.

2021-05-17 16:50 UTC, closed without merging

2021-05-17 17:10 UTC, antalszava commented
Hi @charmerDark, it looks the changes were removed, would you happen to have another copy of your changes locally? That way, you could create a new branch and a new pull request. I've also pulled your changes recently, if that would help. Let me know :slightly_smiling_face:

2021-05-17 17:14 UTC, charmerDark commented
I'll make a new branch and  another pull request. Sorry this has all turned into such a hassle.

2021-05-17 17:18 UTC, antalszava commented
Sure! No worries :slightly_smiling_face: Feel free to tag me and can go for a review.