Fix bug where shots does not reset to None when temporarily changed
PennyLaneAI/pennylane pull request #1392
Opened 2021-06-08 15:31 UTC by mariaschuld

**Context:**

In PR #1075 we introduced a way to temporarily change the shots per call of a qnode. Due to a simple bug, the resetting to original shots value did not work if it was `None`.

**Description of the Change:**

Fix bug, add test.

**Possible Drawbacks:**

The test checks for analytic vs non-analytic behaviour by comparing the variance of a Hadamard circuit's expectation run 100 times, and has a vanishingly small probability of failing (I assume it is 2^100 or so :) - the probability of observing 100 ones or zeros in a coin toss)

2021-06-08 15:45 UTC, albi3ro requested changes
Thanks for getting to this so quickly :)

Looks like we also need to run black on the test file to get the checks to pass.

2021-06-08 15:45 UTC, albi3ro commented on tests/tape/test_qnode.py
> +        assert np.std(res1) == 0.
```suggestion
        assert np.std(res1) == 0.
        assert circuit.device._shots is None
```

2021-06-08 15:45 UTC, albi3ro commented on tests/tape/test_qnode.py
> +        assert np.std(res1) == 0.
```suggestion
        assert np.std(res1) == 0.
        assert circuit.device._shots is None
```

2021-06-09 08:25 UTC, mariaschuld commented
@albi3ro should be fixed now :)

2021-06-09 14:27 UTC, albi3ro approved these changes
:)

2021-06-09 14:27 UTC, merged