Add a warning when calling a QNode with non-tensor positional arguments
PennyLaneAI/pennylane pull request #1470
Opened 2021-07-22 14:59 UTC by antalszava

Closes #1459.

2021-07-22 15:58 UTC, josh146 requested changes
@antalszava this will cause a warning to be raised for behaviour that is already consider acceptable by PL!

E.g.,

```python
@qml.qnode(dev)
def circuit(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

>>> circuit(0.2)
WARNING: 
0.5432543
>>> circuit(np.array(0.2, requires_grad=True))
0.5432543
```

Furthermore, this _only applies to Autograd_.

Hence, we need to be very careful here. I suggest:

1. Making this a VisibleDeprecationWarning (since we are deprecating current PL behaviour).
2. Avoid mentions of 'NumPy tensor', as I think this could be confusing to users.
2. Re-wording the warning to make it clear exactly the change the user has to make; either use `requires_grad=False`, or pass as a keyword argument.

2021-07-22 15:58 UTC, josh146 commented on pennylane/qnode.py
> +                    "arguments as keyword arguments when calling the QNode.",
Suggest rewording this to clarify the change, and avoid mentions of tensors. Something like the following:

```python
f"""VisibleDeprecationWarning: Passing non-differentiable positional arguments to
QNodes without setting requires_grad=False has been deprecated and will be
removed from a future release.

Please specify directly that this argument is non-trainable via np.array({pos_arg}, requires_grad=False),
or for non-numeric arguments consider passing it as a keyword argument."""
```

2021-07-22 15:58 UTC, josh146 commented on pennylane/qnode.py
> +            if not isinstance(pos_arg, qml.numpy.tensor):
This warning should only be raised when using the autograd interface, _not_ pytorch/jax/tf!

2021-07-22 15:59 UTC, josh146 commented on .github/CHANGELOG.md
> +  [(#1470)](https://github.com/PennyLaneAI/pennylane/pull/1470)
This will need to go into breaking changes!

2021-07-22 15:59 UTC, josh146 commented on .github/CHANGELOG.md
> +  [(#1470)](https://github.com/PennyLaneAI/pennylane/pull/1470)
(and re-worded to make the deprecation more explicit)

2021-07-22 16:03 UTC, josh146 commented on pennylane/qnode.py
> +            if not isinstance(pos_arg, qml.numpy.tensor):
In addition, I believe it should check:

1. Whether the positional argument requires grad (via `qml.math.requires_grad`)
2. Only then, if it is not a `np.tensor`, should the warning be raised.

2021-12-19 23:12 UTC, antalszava commented
Closing this as we've made the deprecation another way.

2021-12-19 23:12 UTC, closed without merging