Updated Changelog.md file as required.
PennyLaneAI/pennylane pull request #1478
Opened 2021-07-27 10:24 UTC by arshpreetsingh

Updated changelog.md file.

2021-07-27 14:27 UTC, thisac requested changes
Thanks for adding this. Just a few minor suggestions, and then it should be good to go!

2021-07-27 14:27 UTC, thisac commented on .github/CHANGELOG.md
> +
```suggestion
Building a core PennyLane image:
```

2021-07-27 14:27 UTC, thisac commented on .github/CHANGELOG.md
> +
```suggestion

Building a PennyLane image with the Qiskit plugin (change `plugin-name` for other plugins):
```

2021-07-27 14:27 UTC, thisac commented on .github/CHANGELOG.md
> +
```suggestion

Building a PennyLane-Qchem image:
```

2021-07-27 17:41 UTC, arshpreetsingh commented
> Thanks for adding this. Just a few minor suggestions, and then it should be good to go!

Resolved!

2021-07-28 15:58 UTC, thisac approved these changes
Looks good! 💯

2021-08-08 16:02 UTC, merged