Speed-Up for Hamiltonian Simplification
PennyLaneAI/pennylane pull request #1506
Opened 2021-08-09 02:12 UTC by Lucaman99

**Context:**

**Description of the Change:**

This is a very small change, but this issue has been bugging me for a while. The current method of simplifying Hamiltonians (which I originally implemented, so this is my fault!) is very slow. This change makes it much faster. For example, adding the second-quantized BeH2 Hamiltonian to itself used to take 12 seconds, now it takes 0.06 seconds.

**Benefits:**

Faster arithmetic between Hamiltonians!

**Possible Drawbacks:**

None

**Related GitHub Issues:**

2021-08-09 06:14 UTC, josh146 commented
> For example, adding the second-quantized BeH2 Hamiltonian to itself used to take 12 seconds, now it takes 0.06 seconds.

🤯 

Was this just a matter of avoiding the internal for loop?

By the way @Lucaman99, it looks like some of the tests are still failing - let me know if this PR is still WIP!

2021-08-09 14:32 UTC, Lucaman99 commented
Yes, it's still a WIP, although I'll probably finish it today. It was in fact just a matter of avoiding the internal loop! Basically I just replaced it with a dictionary which stores the index of each term in the list of observables. That way, we don't have to cycle through the list.

2021-08-09 17:27 UTC, Lucaman99 commented
Unfortunately, the speedup is more like 100x rather than 200x now (at least for the case of BeH2), as I forgot to take into account the fact that terms with coefficients equal to 0 need to be eliminated.

2021-08-10 10:20 UTC, josh146 reviewed
Thanks @Lucaman99 for this improvement! Two main comments:

1. It seems that this is causing the QAOA tests to fail?
2. @mariaschuld is currently re-factoring the `simplify` method as part of #1483. It might be good if she can have a look over the logic change, and ensure it is compatible with that PR.

2021-08-10 10:20 UTC, josh146 commented on .github/CHANGELOG.md
> +>>>>>>> 94b930417d22412e3825b7c618669d08ebdcebbc
Merge issue?

2021-08-10 10:48 UTC, mariaschuld commented on pennylane/vqe/vqe.py
> +            ind = ops_coeffs.get(op_id)
I was a bit confused about this line. Don't you just want to know if `op_id` is in  `ops_coeffs` or not? Why would you need `ind` and why the name?

2021-08-10 10:49 UTC, mariaschuld commented on pennylane/vqe/vqe.py
> +            op_id = frozenset(op._obs_data())
Do you use this as a key because it is safer than using the operator? Good idea!

2021-08-10 10:50 UTC, mariaschuld requested changes
I am not sure I understand why it is faster, but it looks safer and cleaner :) 

I can adapt my PR to this, no problem!

Just requesting the change Josh pointed out (plus fixing the tests), but then happy to approve.

2021-12-16 10:39 UTC, josh146 commented
@mariaschuld @Lucaman99 what is the status of this PR?

2021-12-16 11:39 UTC, mariaschuld commented
I'm not sure, but it would be great to have this implemented if it is still valid @Lucaman99 . Let me know if I can help

2021-12-17 14:50 UTC, Lucaman99 commented
Hey @mariaschuld @josh146 - Apologies, I completely forgot about this PR, I'll take a look today and try to get a good version ready for re-review!

2023-11-23 19:53 UTC, trbromley commented
Hi everyone! Thanks @Lucaman99 for the PR.

Due to inactivity, I'm closing this PR and deleting the branch. Feel free to restore and reopen if you'd like to continue working on this, or alternatively you might want to open a new PR :rocket:

2023-11-23 19:53 UTC, closed without merging