Validation check for arguments passed to qml.operation.Observable
PennyLaneAI/pennylane pull request #1539
Opened 2021-08-16 20:53 UTC by mayap24

**Context:**
For Code Together Event
**Description of the Change:**
Validation check for arguments passed to qml.operation.Observable
**Benefits:**
Gives user a clear error message to include arguments

2021-08-16 21:33 UTC, antalszava commented
Hi @mayap24, thank you for opening up this PR! :slightly_smiling_face:

In our testing, we've turned to using `pytest` instead of `unittest`. See this [page for running the test suite](https://pennylane.readthedocs.io/en/stable/development/guide/tests.html) and the [Development guide](https://pennylane.readthedocs.io/en/stable/development/guide.html) for development suggestions.

In terms of organization, it's good to put test cases into a relevant test file within the `tests` directory.

Let us know if you'd have any questions! :slightly_smiling_face:

2021-08-17 19:43 UTC, antalszava commented on tests/test_operation.py
> +      qml.PauliZ()
Hi @mayap24, it seems that something is going wrong with the indentation that causes tests to fail:
https://github.com/PennyLaneAI/pennylane/pull/1539/checks?check_run_id=3354356772#step:10:41

Hopefully, this should help. Also, adding a changelog entry would be required for the PR. See the [Submitting a Pull Request](https://pennylane.readthedocs.io/en/stable/development/guide/pullrequests.html) for more details. Let us know if the PR would be ready for review!
```suggestion
    def test_validation():
        with pytest.raises(Exception, match="Can only access when arguments are passed."):
            qml.PauliZ()
```

2021-08-18 13:44 UTC, antalszava requested changes
Hi @mayap24, thanks for the submission! :slightly_smiling_face: There seem to be some parts that still need adjustments, but overall looking nice!

2021-08-18 13:44 UTC, antalszava commented on .github/CHANGELOG.md
> +* Validation check for arguments passed to qml.operation.Observable gives user a clear error message to include arguments.
Could you add yourself to the list of contributors on line 144?

2021-08-18 13:44 UTC, antalszava commented on tests/test_operation.py
> +    def test_validation():
Since we have the case in a Pytest class, the method takes `self`
```suggestion
    def test_validation(self):
```

2021-08-18 13:44 UTC, antalszava commented on pennylane/operation.py
> +                raise Exception("Can only access when arguments are passed.")
Maybe it's good to be slightly more specific when informing the user. Accepting this new message will also require the test case to be adjusted with the new message.
```suggestion
                raise Exception("Cannot extract wires as no arguments were passed to the observable.")
```

2021-08-18 13:44 UTC, antalszava commented on tests/test_operation.py
> +    """Tests for Validation Check for arguments passed to qml.operation.Observable"""
```suggestion
    """Tests for validating the number of arguments passed to qml.operation.Observable"""
```

2021-08-18 15:36 UTC, antalszava commented
Hi @mayap24, it looks like the formatting check is failing. Could you run `black -l 100 pennylane/` from the external `pennylane` folder?

2021-08-18 15:39 UTC, mayap24 commented
> Hi @mayap24, it looks like the formatting check is failing. Could you run `black -l 100 pennylane/` from the external `pennylane` folder?

2021-08-18 16:42 UTC, antalszava commented
Hi @mayap24, you'd have to run `black -l 100 pennylane/` from the external `pennylane` folder.

2021-08-18 18:31 UTC, antalszava commented
Hi @mayap24, it seems that in the meantime another submission came in that we've accepted for the original #1507  issue. As you were close with your solution, we could still give out digital swag for your participation. :tada:  There are still other open issues labelled with `code together`, should you want to tackle another one and get a PR merged. :slightly_smiling_face:

2021-08-18 18:35 UTC, mayap24 commented
> Hi @mayap24, it seems that in the meantime another submission came in that we've accepted for the original #1507 issue. As you were close with your solution, we could still give out digital swag for your participation. 🎉 There are still other open issues labelled with `code together`, should you want to tackle another one and get a PR merged. 🙂

Ah okay, thank you so much! :)

2021-08-18 18:38 UTC, antalszava commented
No worries! I'll be closing this PR, but let us know if you have any questions. :)

2021-08-18 18:38 UTC, closed without merging