[Code Together] Add a deprecation warning for `qml.Interferometer` before renaming
PennyLaneAI/pennylane pull request #1546
Opened 2021-08-17 17:52 UTC by AkashNarayanan

**Context:**
 Add a deprecation warning for `qml.Interferometer` and a test case to check the warning

**Description of the Change:**
- Added a `UserWarning` with a deprecation message to the `ops.cv.Interferometer` class explaining that it will be renamed to `InterferometerUnitary`.
- Added a test case to check if a warning is raised when creating the operation

**Benefits:**
Informs users about the deprecation of `Interferometer`.

**Related GitHub Issues:**
#1531

2021-08-17 19:31 UTC, thisac commented
Thanks @AkashNarayanan for working on this! We'll have a look at the PR and review it soon.

2021-08-18 15:45 UTC, thisac requested changes
Thanks @AkashNarayanan! Just a small comment on the formatting. Looks great otherwise!

2021-08-19 04:08 UTC, AkashNarayanan commented on pennylane/ops/cv.py
> +import warnings
Thank you for the feedback @thisac ! I have already changed the import order and have pushed it to the branch (39e5247ec7708433af29548f4f51b5709402963f). I will make the remaining suggested changes and push them soon.

2021-08-19 05:01 UTC, AkashNarayanan commented
Hi @thisac ! I have made the suggested changes.

2021-08-19 14:11 UTC, thisac commented
Hi @AkashNarayanan! Thanks for making the changes. Looks good, so I'll approve and merge. 💯

2021-08-19 14:11 UTC, thisac approved these changes

2021-08-19 14:11 UTC, merged