[WIP] Adding SISWAP operation
PennyLaneAI/pennylane pull request #1563
Opened 2021-08-19 21:25 UTC by charmerDark

I've just added the SISWAP class, but I am having trouble exposing it as `qml.SISWAP` . I tried following the [PR for ISWAP](https://github.com/PennyLaneAI/pennylane/pull/1298/files). But I think the code structure has changed a bit since then? Could you please help me out on this end?

2021-08-19 21:35 UTC, antalszava commented
Hi @charmerDark, after checking out your branch I could access `qml.SISWAP` :thinking: Was there a particular place in the codebase where it was not working?

The operations have indeed been split across files. If a new op is added to one of the existing files, it should be imported by in the top level `__init__.py` file.

2021-08-20 16:47 UTC, charmerDark commented
Hey @antalszava !
I hadn't added any tests for SQISW because it redirects to SISWAP class. Also should I mention SQISW in the documentation line for SISWAP?

2021-08-20 17:00 UTC, antalszava commented
Hi @charmerDark, just for extra safety, cases could be added for `qml.SQISW` too, similar to how it's the case for `CPhase`:
* https://github.com/PennyLaneAI/pennylane/blob/e44a3274a30b4ec6597b198703e306d25d8f7886/tests/ops/test_qubit_ops.py#L431
* https://github.com/PennyLaneAI/pennylane/blob/e44a3274a30b4ec6597b198703e306d25d8f7886/tests/ops/test_qubit_ops.py#L1556

It's mostly a matter of adding the same test case as for `qml.SISWAP`, just calling `qml.SQISW`.

> Also should I mention SQISW in the documentation line for SISWAP?

Yep, it could also be added to `doc/introduction/operations.rst`, just is the case with `CPhase`.

2021-08-20 17:01 UTC, antalszava commented on pennylane/ops/__init__.py
> +
```suggestion
```

2021-08-21 06:12 UTC, charmerDark commented
Hey @antalszava
Could you see if its all right now? Thanks in advance

2021-08-23 14:23 UTC, antalszava requested changes
Hi @charmerDark, this is getting there! :tada: Left some suggestions, but the main addition is looking nice. :slightly_smiling_face:

2021-08-23 14:23 UTC, antalszava commented on pennylane/ops/qubit/non_parametric_ops.py
> +    The square root of i-swap operator. Can also be accessed as `qml.SQISW`
```suggestion
    The square root of i-swap operator. Can also be accessed as ``qml.SQISW``
```

2021-08-23 20:46 UTC, antalszava commented on .github/CHANGELOG.md
> +* New SISWAP operation added to default_qubit device. Also added associated test [#1563](https://github.com/PennyLaneAI/pennylane/pull/1563)
```suggestion
* Added a new `SISWAP` operation and a `SQISW` alias with support to the `default_qubit` device.
  [#1563](https://github.com/PennyLaneAI/pennylane/pull/1563)
```

2021-08-23 22:26 UTC, antalszava approved these changes
Hi @charmerDark, this is looking great! :tada: Thank you for the addition and for following through the review process. :blush: :1st_place_medal:

2021-08-23 22:27 UTC, merged