Add basis set functions for HF solver
PennyLaneAI/pennylane pull request #1582
Opened 2021-08-23 18:34 UTC by soranjh

**Context:**
This PR adds a class and functions needed to create a basis function object and generate default basis set parameters. The basis function object holds the basis set parameters and is used as input to compute various integrals over basis functions, such as the overlap integral, that are needed to perform a Hartree-Fock calculation.

**Description of the Change:**
The BasisFunction class is added to creates basis function objects and the functions atom_basis_data and mol_basis_data are added to generate the default basis set parameters. The parameters of the STO-3G basis set, including the exponents and contraction coefficients of the Gaussian functions and the angular momentum numbers, are stored in a dictionary for atoms with atomic numbers 1-10. The parameter set can be easily extended to contain more atoms and more basis sets.

**Benefits:**
The BasisFunction object makes the basis set parameters easy to handle and manipulate. Having the default basis set parameters makes PL independent of external libraries, such as the Basis Set Exchange [library](https://www.basissetexchange.org/), for generating basis set data. Note that the users still have the option of using their own basis set data imported from any desired library in case they prefer not to use the default parameters provided in this PR. 

**Possible Drawbacks:**
No specific drawbacks.

**Related GitHub Issues:**
No related issues.

2021-08-24 15:30 UTC, rmoyard reviewed
Nice PR, my main comment would be to create an `__init__.py` in both `pennylane_qchem` and `hf`, then it is possible to use `hf` function outside this scope. By doing this you can also move the `test_basis_set.py`file to the main `tests`folder. I have something almost ready if you agree with that. You can also add the change to the qchem `CHANGELOG.md`.

2021-08-24 15:30 UTC, rmoyard commented on qchem/pennylane_qchem/hf/basis_set.py
> +    >>>  n_basis, params = mol_basis_data('sto-3g', ['H', 'H'])
```suggestion
    >>> n_basis, params = mol_basis_data('sto-3g', ['H', 'H'])
```

2021-08-24 20:37 UTC, agran2018 requested changes
Thank you @soranjh! I have left some suggestions. Very interesting PR.

2021-08-24 20:37 UTC, agran2018 commented on qchem/pennylane_qchem/hf/basis_set.py
> +    This function extracts the default angular momentum and the exponents and contraction
What do you mean by `default` angular momentum?

2021-08-24 20:37 UTC, agran2018 commented on qchem/pennylane_qchem/hf/basis_set.py
> +    p = [(0, 0, 1), (0, 1, 0), (1, 0, 0)]
is the convention here px = (1, 0, 0), py = (0, 1, 0), pz = (0, 0, 1) ?

2021-08-24 20:37 UTC, agran2018 commented on qchem/pennylane_qchem/hf/basis_set.py
> +    return params
Nice!

2021-08-24 20:37 UTC, agran2018 commented on qchem/pennylane_qchem/hf/basis_set.py
> +        tuple(list, tuple): the number of basis functions and the basis set parameters for each atom
```suggestion
        tuple(list, tuple): the number of atomic basis functions and the basis set parameters for each atom
```

2021-08-24 20:37 UTC, agran2018 commented on qchem/pennylane_qchem/hf/basis_set.py
> +    """
May we use for the example a molecule with two different atoms e.g., LiH?  A less symmetric output might be more clarifying.

2021-08-30 16:11 UTC, soranjh commented
> 2. Have a _different_ module name for the built-in qchem components of PennyLane.

@josh146, @rmoyard, I have created the qchem_hf module in pennylane to store the differentiable HF functions. Any thoughts?

2021-08-30 16:15 UTC, josh146 commented
> I have created the qchem_hf module in pennylane to store the differentiable HF functions. Any thoughts?

Nice 👍 Only suggestion I have is minor, but `pennylane.hf` is quite concise and nice sounding to my ears!

Don't forget to move the changelog entry to the PL changelog :)

2021-08-30 16:17 UTC, soranjh commented
> > I have created the qchem_hf module in pennylane to store the differentiable HF functions. Any thoughts?
> 
> Nice  Only suggestion I have is minor, but `pennylane.hf` is quite concise and nice sounding to my ears!
> 
> Don't forget to move the changelog entry to the PL changelog :)

Agree. Thanks Josh.

2021-08-30 16:26 UTC, rmoyard commented
@soranjh Yes I think it is a good solution and agree with Josh !

2021-08-30 19:03 UTC, rmoyard reviewed
You just forgot to change the name in the import 👍

2021-08-30 19:03 UTC, rmoyard commented on pennylane/hf/basis_set.py
> +from pennylane.qchem_hf.basis_data import STO3G
```suggestion
from pennylane.hf.basis_data import STO3G
```

2021-08-30 19:03 UTC, rmoyard commented on tests/hf/test_basis_set.py
> +from pennylane.qchem_hf.basis_set import BasisFunction, atom_basis_data, mol_basis_data
```suggestion
from pennylane.hf.basis_set import BasisFunction, atom_basis_data, mol_basis_data
```

2021-08-31 16:20 UTC, merged