[WIP] add normalisation functions for HF solver
PennyLaneAI/pennylane pull request #1616
Opened 2021-08-31 23:35 UTC by soranjh

**Context:**
This PR adds functions to compute normalisation constant for primitive and contracted Gaussian functions. 

**Description of the Change:**
`primitive_norm` and `contracted_norm` are added to compute normalisation constant for primitive and contracted Gaussian functions, respectively

**Benefits:**
These functions are necessary for computing accurate integrals over basis functions.

**Possible Drawbacks:**
No specific drawbacks.

**Related GitHub Issues:**
No related issues.

2021-09-02 14:07 UTC, agran2018 requested changes
Thank you @soranjh! Left some suggestions to improve consistency of the code with the docstrings.

2021-09-02 14:07 UTC, agran2018 commented on pennylane/hf/integrals.py
> +    lx, ly, lz = l
Probably it is easier to change the notation in the docstring for consistency. For example:

> G = x^l y^m z^n e^{-\alpha r^2}  ==>> G = x^l_x y^l_y z^l_z e^{-\alpha r^2}

2021-09-02 14:07 UTC, agran2018 commented on pennylane/hf/integrals.py
> +        / anp.sqrt(fac2(2 * lx - 1) * fac2(2 * ly - 1) * fac2(2 * lz - 1))
so many different Numpies :-)

2021-09-02 14:07 UTC, agran2018 commented on pennylane/hf/integrals.py
> +    where :math:`a` denotes the contraction coefficients and :math:`G` is a Gaussian function. The
```suggestion
    where :math:`a` denotes the contraction coefficients and :math:`G` is a primitive Gaussian function. The
```

2021-09-02 14:07 UTC, agran2018 commented on pennylane/hf/integrals.py
> +        n (array[float]): normalization coefficient
same comment here, any reason for `n` to be an array?

2021-09-02 14:07 UTC, agran2018 commented on pennylane/hf/integrals.py
> +    n = 1 / anp.sqrt(c * s)
Indeed, it is not an array.

2021-09-02 18:53 UTC, soranjh commented on pennylane/hf/integrals.py
> +        alpha (array[float]): exponent of the primitive Gaussian function
When `\alpha` is a differentiable parameter it has the format of a pennylane numpy array and each component of the array has the same format. 
```
from pennylane import numpy as pnp
alpha = pnp.array([3.42525091, 0.62391373, 0.1688554])
alpha[0]  # tensor(3.42525091, requires_grad=True)
```
Same applies to the rest of occasions pointed to below.

2021-09-02 21:11 UTC, agran2018 approved these changes
Thank you @soranjh. Looks good on my side.

2021-09-03 20:36 UTC, rmoyard reviewed
Great PR, I've left some comments about the docstrings

2021-09-03 20:36 UTC, rmoyard commented on pennylane/hf/integrals.py
> +        G = x^l_x y^l_y z^l_z e^{-\alpha r^2},
```suggestion
        G = x^{l_x} y^{l_y} z^{l_z} e^{-\alpha r^2},
```
I am not sure it renders correctly without the {}.

2021-09-03 20:36 UTC, rmoyard commented on pennylane/hf/integrals.py
> +    array([1.79444183])
```suggestion
    **Example**
    
    >>> l = (0, 0, 0)
    >>> alpha = np.array([3.425250914])
    >>> n = gaussian_norm(l, alpha)
    >>> print(n)
    
    array([1.79444183])
```

2021-09-03 20:36 UTC, rmoyard commented on pennylane/hf/integrals.py
> +        {(2\l_x-1)!! (2\l_y-1)!! (2\l_z-1)!!)^{1/2}}.
Is that correct to use \l ?

2021-09-03 20:36 UTC, rmoyard commented on pennylane/hf/integrals.py
> +        N(l, \alpha, a) = [\frac{\pi^{3/2}(2\l_x-1)!! (2\l_y-1)!! (2\l_z-1)!!}{2^{l_x + l_y + l_z}}
Same comment as before with \l.

2021-09-03 20:36 UTC, rmoyard commented on pennylane/hf/integrals.py
> +    >>> print(n)
```suggestion
    **Example**
    
    >>> l = (0, 0, 0)
    >>> alpha = np.array([3.425250914, 0.6239137298, 0.168855404])
    >>> a = np.array([1.79444183, 0.50032649, 0.18773546])
    >>> n = contracted_norm(l, alpha, a)
    >>> print(n)
    
```

2021-09-03 22:11 UTC, merged