Adjust Torch and TF backprop docstrings
PennyLaneAI/pennylane pull request #1662
Opened 2021-09-16 18:03 UTC by antalszava

2021-09-17 12:05 UTC, albi3ro requested changes

2021-09-17 12:05 UTC, albi3ro commented on pennylane/devices/default_qubit_tf.py
> +      outputs will result in an error.
Maybe:

```
    * Only exact expectation values, variances, and probabilities are differentiable.
      Creation of a backpropagation QNode with finite shots raises an error. If you do try
      and take a derivative with finite shots on this device, the gradient will be ``None``.
```

2021-09-20 10:39 UTC, antalszava commented on pennylane/devices/default_qubit_tf.py
> +      outputs will result in an error.
Great catch @albi3ro, thank you :slightly_smiling_face: Adjusted it as suggested.

2021-09-20 15:50 UTC, albi3ro approved these changes
thanks :)

2021-09-20 16:13 UTC, merged