[WIP] Multi amplitude embedding with transform
PennyLaneAI/pennylane pull request #1933
Opened 2021-11-24 11:46 UTC by KetpuntoG

**Context:** In certain situations it may be convenient to be able to use more than one `amplitudeEmbedding` in the same circuit. A first approximation has been made but it has been decided to use circuit transformations to merge these gates. [(#1890)](https://github.com/PennyLaneAI/pennylane/pull/1890)

**Description of the Change:** A `merge_amplitude_embedding` transformation has been created, which takes a quantum function and returns it transformed by joining all gates of this type together.

**Example:**

```python
import pennylane as qml
from pennylane.transforms import merge_amplitude_embedding

@merge_amplitude_embedding
def qfunc():
    
    qml.AmplitudeEmbedding([0,1,0,0], wires = [0,1])
    qml.AmplitudeEmbedding([0,1], wires = 2)
    
    return qml.expval(qml.PauliZ(wires = 0))

dev = qml.device("default.qubit", wires = 3)
qnode = qml.QNode(qfunc, dev)
print(qml.draw(qnode)())
```

 0: ──╭AmplitudeEmbedding(M0)──┤ ⟨Z⟩ 
 1: ──├AmplitudeEmbedding(M0)──┤     
 2: ──╰AmplitudeEmbedding(M0)──┤     
M0 =
[0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

**Benefits:**

Convenience when programming some routines such as the calculation of the internal product through the swap test.

**Possible Drawbacks:**

**Related GitHub Issues:**
[(#1140)](https://github.com/PennyLaneAI/pennylane/issues/1140)

2021-11-24 15:44 UTC, KetpuntoG commented
[sc-11240]

2021-11-24 18:46 UTC, antalszava requested changes
Hi @KetpuntoG, this is amazing, looks great! Congrats and thank you for hanging in there through the extra required changes :blush: :tada: 

Nothing major for the PR, one test case that I think could be useful to add is a case where a QNode is being decorated and it's checked that evaluating it works as expected (and as proposed in the original issue).

2021-11-24 18:46 UTC, antalszava commented on tests/transforms/test_optimization/test_merge_amplitude_embedding.py
> +    """Test that amplitude merging works in all interfaces."""
```suggestion
    """Test that merging amplitude embedding operations works in all interfaces."""
```

2021-11-24 18:46 UTC, antalszava commented on tests/transforms/test_optimization/test_merge_amplitude_embedding.py
> +
```suggestion
```

2021-11-24 18:46 UTC, antalszava commented on tests/transforms/test_optimization/test_merge_amplitude_embedding.py
> +        """Test that the transformation is working correctly by joining two amplitudeEmbedding."""
```suggestion
        """Test that the transformation is working correctly by joining two AmplitudeEmbedding."""
```

2021-11-25 23:25 UTC, antalszava commented on tests/transforms/test_optimization/test_merge_amplitude_embedding.py
> +        assert qnode()[3] == 1.0
```suggestion
        dev = qml.device("default.qubit", wires=3)
        
        @merge_amplitude_embedding
        @qml.qnode(dev)
        def qnode():
            qml.AmplitudeEmbedding([0, 1, 0, 0], wires=[0, 1])
            qml.AmplitudeEmbedding([0, 1], wires=2)

            return qml.state()

        assert qnode()[3] == 1.0
```

2021-11-25 23:26 UTC, antalszava approved these changes
Looks great! :partying_face: Thank you again for the great solution. :tada:

2021-11-26 08:30 UTC, merged