undo_swaps
PennyLaneAI/pennylane pull request #1960
Opened 2021-12-01 10:52 UTC by KetpuntoG

**Context:** The `Permute` operation uses many SWAP gates to be implemented. In [(#1324)](https://github.com/PennyLaneAI/pennylane/issues/1324) a study was proposed to make this operator native to `default_qubit` in order to make the circuit more efficient. Instead, I have created a transformation that removes all the SWAP gates from the circuit by playing with the wires of the operations. I think it is a more efficient and flexible solution. 

**Description of the Change:** 
With a single reading of the circuit from right to left, all SWAPS in the circuit can be eliminated.

**Example**:

Without `undo_swaps`:

```python
import pennylane as qml
dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def qfunc():
    qml.Hadamard(wires=0)
    qml.PauliX(wires=1)
    qml.SWAP(wires=[0,1])
    qml.SWAP(wires=[0,2])
    qml.PauliY(wires=0)
    return qml.expval(qml.PauliZ(0))

print(qml.draw(qfunc)())
```
 0: ──H──╭SWAP──╭SWAP──Y──┤ ⟨Z⟩ 
 1: ──X──╰SWAP──│────────┤     
 2: ──────────╰SWAP─────┤  

With `undo_swaps`:

```python
@qml.qnode(dev)
@qml.transforms.undo_swaps
def qfunc():
    qml.Hadamard(wires=0)
    qml.PauliX(wires=1)
    qml.SWAP(wires=[0,1])
    qml.SWAP(wires=[0,2])
    qml.PauliY(wires=0)
    return qml.expval(qml.PauliZ(0))

print(qml.draw(qfunc)())
```

 0: ──Y──┤ ⟨Z⟩ 
 1: ──H──┤     
 2: ──X──┤

**Benefits:** 
The computational cost of the circuit calculation is reduced.

**Related GitHub Issues:**
[(#1324)](https://github.com/PennyLaneAI/pennylane/issues/1324)

2021-12-01 12:44 UTC, josh146 commented
very nice solution!

2021-12-01 13:46 UTC, KetpuntoG commented
> very nice solution!

Thanks @josh146 😊

2021-12-01 13:49 UTC, KetpuntoG commented
[sc-11831]

2021-12-01 18:20 UTC, dime10 requested changes
Hey @KetpuntoG, thank you for contributing this transform, great idea for an optimization :)

A few minor comments below.

2021-12-01 18:20 UTC, dime10 commented on pennylane/transforms/optimization/undo_swaps.py
> +            continue
I think you can remove the continue here as it's the last statement in the loop.

2021-12-01 18:20 UTC, dime10 commented on tests/transforms/test_optimization/test_undo_swaps.py
> +        """Test that a two-qubit gate change correctly with a SWAP."""
```suggestion
        """Test that a two-qubit gate changes correctly with a SWAP."""
```

2021-12-02 09:23 UTC, KetpuntoG commented on tests/transforms/test_optimization/test_undo_swaps.py
> +            qml.CNOT(wires=[0, 1])
the thing is that the PauliX is going to change to one (assuming it passes the above test) 😄

2021-12-02 09:44 UTC, dime10 commented on tests/transforms/test_optimization/test_undo_swaps.py
> +            qml.CNOT(wires=[0, 1])
But only on the target wire right, not the control wire?

2021-12-02 09:44 UTC, KetpuntoG commented on pennylane/transforms/__init__.py
> +    undo_swaps,
Oh that's right! Josh is going to kill me haha

2021-12-02 09:50 UTC, dime10 commented on pennylane/transforms/optimization/undo_swaps.py
> +    """Quantum function transform to remove SWAP gates. To do this it runs from right to left through the circuit changing the position of the qubits accordingly.
```suggestion
    """Quantum function transform to remove SWAP gates. To do this it runs from right
    to left through the circuit changing the position of the qubits accordingly.
```
Probably want to wrap this a bit :)

2021-12-02 10:01 UTC, KetpuntoG commented on tests/transforms/test_optimization/test_undo_swaps.py
> +            qml.CNOT(wires=[0, 1])
I mean, we have:
-----C----SWAP
X----X-----SWAP

what I want to check is that it does not transform itself to:

  X---C---
    ---X----

2021-12-02 10:19 UTC, dime10 commented on tests/transforms/test_optimization/test_undo_swaps.py
> +            qml.CNOT(wires=[0, 1])
Ah ok, I understand now :D

2021-12-02 10:21 UTC, dime10 approved these changes

2021-12-02 10:44 UTC, josh146 commented on pennylane/transforms/__init__.py
> +    undo_swaps,
👀

2021-12-02 16:19 UTC, merged