`qml.RandomLayers` decomposes with list of lists weights
PennyLaneAI/pennylane pull request #2266
Opened 2022-03-03 00:18 UTC by albi3ro

Fixes #2261 

`qml.RandomLayers` raised a `TypeError` upon decomposition when the weights were a list of lists, like `[[0.1, 0.2, 0.3]]`.

Now it works as expected.

2022-03-03 00:19 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +
```suggestion
  [(#2266)](https://github.com/PennyLaneAI/pennylane/pull/2266/)

```

2022-03-03 18:10 UTC, antalszava requested changes
This fix looks great! :100: The test case is a great unit test to make sure that decomposition works now.

A change that would be great to have on top is to add the original non-working example as an integration test. The idea would be to make sure that the execution doesn't raise an error anymore, so we could simply assert the shape of the output.

Minor thing: `weights` seems to be documented as tensor-like, I wonder if list of lists falls into that category? Should the docstring be extended?

2022-03-03 19:46 UTC, albi3ro commented
@antalszava I think having an integration test for this case is overkill, especially since we don't need to test differentiability.  Part of good tests is having them fast, so I think the minimal unit test is more warranted in this situation. 

Before today, the documentation example was a list of lists.  In the PR updating docstrings for the drawer I changed the weights to a numpy array to get the example to execute. We can always support lists of lists without explicitly encouraging people to pass in parameters that way, so I don't think we need to update the documentation.

2022-03-03 19:57 UTC, antalszava approved these changes
Cool, thanks! :100: If the example in the docs was changed, then this looks good to go.

2022-03-03 20:54 UTC, merged

2022-03-09 18:47 UTC, albi3ro commented
[sc-15477]