Move interfaces and interface tests out of the batch folder
PennyLaneAI/pennylane pull request #2337
Opened 2022-03-16 06:15 UTC by josh146

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-03-16 06:25 UTC, josh146 commented on pennylane/interfaces/__init__.py
> +capabilities with different machine learning libraries.
Note: this file was moved without modification from `pennylane/interfaces/batch/__init__.py`.

2022-03-16 20:41 UTC, albi3ro requested changes
Two main things:

1) We should create a new file `execute.py` for the functions defined in the `__init__.py`.  The `__init__.py` file should be for controlling namespacing, not for defining new, long, and rather important functions.

2) I'm even wondering about the name of the `interfaces` module.  The name makes sense for the interface-specific functions, but I still wouldn't think to find the `execute` function there.  We could either make `pennylane/execute.py` it's own top-level module and restrict `interfaces` to the interface-specific files, or rename the `interfaces` module entirely.  Though I can't come up with a suitably good replacement.

I'm requesting changes because of the presence of code in the `__init__.py` file.

2022-03-17 10:00 UTC, josh146 commented
> I'm requesting changes because of the presence of code in the __init__.py file.

@albi3ro this is already done in #2338 (have also tagged you for review here) 🙂 

I split it into separate PRs to make the code review easier.

2022-03-17 13:26 UTC, albi3ro commented
@josh146 Just seeing that this morning. Sorry for reviewing in the wrong order. Once that's merged I'll approve this.

2022-03-17 14:18 UTC, josh146 commented
> @josh146 Just seeing that this morning. Sorry for reviewing in the wrong order. Once that's merged I'll approve this.

No worries @albi3ro! Although I was hoping to merge this into master first, and then #2338, in order to avoid the squash commit, if that's okay

2022-03-22 03:12 UTC, merged