modified `__add__` for `Observable` and `Hamiltonian` to support adding `0`
PennyLaneAI/pennylane pull request #2603
Opened 2022-05-22 21:19 UTC by Qi-Hu

**Context:**

We would like to be able to sum over a list of observables as follows:
```
H = sum([qml.PauliX(i) for i in range(10)])
```
Since `sum` starts at integer `0` by default, we need to define addition between observables and `0`.

**Description of the Change:**

We modified the `__add__` method for `Observable` and `Hamiltonian` classes, so that integer `0` can be added to those objects, either from the left side or the right side. Unit tests were added for this feature.

**Benefits:**

Now we can directly `sum` a list of observables in an elegant way.

**Possible Drawbacks:**

None.

**Related GitHub Issues:**

Closes #2423.

2022-05-24 17:19 UTC, Qi-Hu commented
> Hi @Qi-Hu, let us know when the PR is ready for review, or if you have any questions 🙂

Hi @co9olguy, this PR is ready for review. Thanks!

2022-05-25 14:39 UTC, antalszava requested changes
Hi @Qi-Hu, the core solution is looking great overall! :tada: :slightly_smiling_face: Great to have support for adding `0` to observables both from the left side and the right side.

There's one subtlety that would be great to adjust and a couple of additional things to test. 

1. The in-place summation  (`__iadd__` method) of the `qml.Hamiltonian` class has a different implementation to the regular addition (`__add__` method).

Although not explicitly mentioned in the original issue, attempting to add `0` to a Hamiltonian object using in-place addition raises an error:
```python
H = sum([qml.PauliX(i) for i in range(10)])
H += 0
```
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-2918b18b0578> in <module>
----> 1 H += 0

~/pennylane/pennylane/ops/qubit/hamiltonian.py in __iadd__(self, H)
    620             return self
    621 
--> 622         raise ValueError(f"Cannot add Hamiltonian and {type(H)}")
    623 
    624     def __imul__(self, a):

ValueError: Cannot add Hamiltonian and <class 'int'>
```
2. As for testing, it would be great to add a couple of further cases:

A. Checking two remaining qubit observables:
* SparseHamiltonian
* Projector

B. Testing the in-place addition support via the `+=` operator for a few general observables.

C. Testing that the feature works for continuous-variable (CV) observables too. These observables would subclass `CVObservable`.

2022-05-25 14:39 UTC, antalszava commented on pennylane/ops/qubit/hamiltonian.py
> +    __radd__ = __add__
Nice :)

2022-05-25 14:39 UTC, antalszava commented on tests/test_operation.py
> +        assert obs.compare(0 + obs)
Great to check both!

2022-05-26 05:25 UTC, Qi-Hu commented
Hi @antalszava, thanks a lot for your detailed comments and useful suggestions! I have made a few changes according to your suggestions.

I have two questions:
1. The `__iadd__` method is only explicitly defined for the `Hamiltonian` class. Do we need to test it for general observables?
2. I added more test cases for the `__add__` method of `Observable` class, including `SparseHamiltonian`, `Projector` and `CVObservable`. However, there were a few test failures. They seemed to be caused by the same issue, which is related to the attribute 'tobytes'. I haven't figured out why this happened, but I will continue working on it.

```
pennylane/operation.py:1635: in compare
    return other._obs_data() == self._obs_data()
pennylane/operation.py:1598: in _obs_data
    parameters = tuple(param.tobytes() for param in ob.parameters)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7fc90b25a850>

>   parameters = tuple(param.tobytes() for param in ob.parameters)
E   AttributeError: 'float' object has no attribute 'tobytes'

pennylane/operation.py:1598: AttributeError
```

2022-05-30 06:55 UTC, Qi-Hu commented
Hi @antalszava, I realized the `compare` method is not supported by a few classes: `Projector`, `SparseHamiltonian`, `QuadOperator` and `FockStateProjector`. To be more specific, their parameters do not have `tobytes` attribute. I do not know if this is an issue that needs to be fixed, so I just didn't include these test cases in my most recent commit.

2022-06-03 20:12 UTC, merged

2022-06-03 20:12 UTC, antalszava commented
Sure :slightly_smiling_face: Merged it, thank you for this contribution! :tada:

2022-06-03 20:15 UTC, Qi-Hu commented
> Sure 🙂 Merged it, thank you for this contribution! 🎉

Glad to hear that! Thank you for your help!

2022-06-03 21:53 UTC, co9olguy commented
:tada: