Fix kwargs for fidelity
PennyLaneAI/pennylane pull request #2740
Opened 2022-06-16 20:49 UTC by rmoyard

**Context:**

This PR fixes the use of dictionnary in the tuple argument.

2022-06-16 21:07 UTC, albi3ro commented on pennylane/qinfo/transforms.py
> +    >>> fidelity(circuit_rx, circuit_ry, wires0=[0], wires1=[0])((0.1, 0.3), (0.9, {'use_ry': True})))
```suggestion
    >>> fidelity(circuit_rx, circuit_ry, wires0=[0], wires1=[0])((0.1, 0.3), (0.9, {'use_ry': True}))
```

2022-06-16 21:10 UTC, albi3ro requested changes
unmatched `)`

2022-06-16 21:16 UTC, albi3ro approved these changes
Thanks for the quick fix.

2022-06-16 21:39 UTC, merged

2022-06-17 00:37 UTC, josh146 commented on pennylane/qinfo/transforms.py
> +    There is also the possibility to pass a single dictionnary at the end of the tuple for fixing args,
```suggestion
There is also the possibility to pass a single dictionary at the end of the tuple for fixing args,
```

2022-06-17 00:38 UTC, josh146 commented on pennylane/qinfo/transforms.py
> +    There is also the possibility to pass a single dictionnary at the end of the tuple for fixing args,
oops, I just realized the PR is already merged 😆