Improve performance of `qml.expval` using op. arithmetic
PennyLaneAI/pennylane pull request #3063
Opened 2022-09-15 09:07 UTC by AlbertMitjans

- Remove expensive unitary check.

2022-09-15 10:17 UTC, AlbertMitjans commented
Time taken to compute `qml.expval` of a `Sum` of 20 `Prod` operators containing `x` random factors in 10 different wires:

- Before:
![image](https://user-images.githubusercontent.com/49232747/190379038-f0fc1c90-8153-4306-abc5-6923ea892595.png)

- After:
![image](https://user-images.githubusercontent.com/49232747/190379062-ed82e38b-8d85-4b92-9cd5-7bd554850d14.png)

2022-09-16 19:22 UTC, albi3ro commented on pennylane/ops/qubit/matrix_ops.py
> +                    + "to act on {len(wires)} wires."
```suggestion
                    + f"to act on {len(wires)} wires."
```

Error message changed to `ValueError: Input unitary must be of shape (2, 2) or (batch_size, 2, 2) to act on {len(wires)} wires.`

the `{len(wires)}` wasn't filled in.

2022-09-16 19:25 UTC, albi3ro commented on pennylane/ops/qubit/matrix_ops.py
> +    def __init__(self, *params, wires, do_queue=True, unitary_check=True):
```suggestion
    def __init__(self, U, wires, do_queue=True, unitary_check=True, id=None):
```

2022-09-16 19:27 UTC, Jaybsoni submitted a review, later dismissed
Nice and quick little improvement 👍🏼! 

Just missing a changelog entry and still need to update the class doc-string for `QubitUnitrary` to mention this new kwarg. It seems that its also missing a section for `Returns` and `Raises` where we list the class instance and the value error + user warning that instantiation of this class can raise.

2022-09-16 19:27 UTC, Jaybsoni commented on pennylane/ops/qubit/matrix_ops.py
> +                    + "to act on {len(wires)} wires."
I don't think you need the plus here? Anyways just a suggestion. 
```suggestion
                      "to act on {len(wires)} wires."
```

2022-09-16 19:27 UTC, albi3ro requested changes
Required changes:

1) Add `unitary_check` and `Keyword Args:` to the docstring for the class. 
2) Fix the warning message.

2022-09-16 19:57 UTC, mlxd requested changes
Small change request from my side

2022-09-16 19:57 UTC, mlxd commented on pennylane/ops/qubit/matrix_ops.py
> +    def __init__(self, *params, wires, do_queue=True, unitary_check=True):
```suggestion
    def __init__(self, *params, wires, do_queue=True, unitary_check=False):
```

I think we discussed the idea for unitarity checks at the start of Q3 and decided it was too much overhead. I think this should be defaulted to off, and only enabled if a user wants verification of the workload.

2022-09-19 08:03 UTC, AlbertMitjans commented on pennylane/ops/qubit/matrix_ops.py
> +    def __init__(self, *params, wires, do_queue=True, unitary_check=True):
Done!

2022-09-19 08:10 UTC, AlbertMitjans commented
> Nice and quick little improvement 👍🏼!
> 
> Just missing a changelog entry and still need to update the class doc-string for `QubitUnitrary` to mention this new kwarg. It seems that its also missing a section for `Returns` and `Raises` where we list the class instance and the value error + user warning that instantiation of this class can raise.

Added changelog entry and docs for the keyword arguments and the error/warning. I don't think we use a `Returns` section for class constructors in PL.

2022-09-19 08:41 UTC, AlbertMitjans commented
[sc-26108]

2022-09-20 14:43 UTC, antalszava commented
Codecov report is incorrect, overriding.

2022-09-20 14:44 UTC, merged