[WIP] qchem openfermion Hamiltonian complex coefficient tolerance
PennyLaneAI/pennylane pull request #3367
Opened 2022-11-16 14:27 UTC by soranjh

**Context:**
The `import_operator` function, which converts an openfermion operator to a PennyLane operator, has a tolerance for discarding the imaginary part of the input operator. Coefficients with imaginary part less than the tolerance are considered to be real. The default tolerance is currently  `2.22e-08` which makes the conversion to fail often. This PR decreases the tolerance to `2.22e-04` and converts the error to a warning when the input openfermion operator has a coefficient with an imaginary component smaller than this value.

**Description of the Change:**

- The default value for the `tol` argument is changed from `1e08` to `1e012`. This value will be used in `numpy.real_if_close` as `tol * machine epsilon`.
- The error is changed to warning.

**Benefits:**
The user is informed about having non-real coefficients in the operator without failing the conversion. 

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-11-17 17:47 UTC, soranjh commented on pennylane/qchem/convert.py
> -        1 + max([max([i for i, _ in t]) if t else 1 for t in qubit_operator.terms])
Fix requested by pylint.

2022-11-24 16:02 UTC, obliviateandsurrender requested changes
Looking good @soranjh, leaving a couple of suggestions.

2022-11-24 16:02 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +    h_pl = qml.qchem.convert.import_operator(h_of, wires=wires, tol=convert_tol)
🚀🚀

2022-11-24 16:02 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +        convert_tol (float): Tolerance in machine epsilons for the imaginary part of the
We might want to provide a link to the machine epsilons here? (if it exists)

2022-11-24 21:49 UTC, obliviateandsurrender approved these changes

2022-12-12 03:40 UTC, merged