[WIP]  Move code from qml.utils.sparse_hamiltonian to Hamiltonian.sparse_matrix #3236
PennyLaneAI/pennylane pull request #3585
Opened 2022-12-27 13:50 UTC by 12mB7693

…trix, added a deprecation warning to qml.utils.sparse_hamiltonian

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-01-03 13:00 UTC, albi3ro commented on pennylane/ops/qubit/hamiltonian.py
>  from typing import List
```suggestion
import functools
from typing import List


import scipy


```

2023-01-03 13:00 UTC, albi3ro commented on pennylane/ops/qubit/hamiltonian.py
> +        matrix += sum(temp_mats)
```suggestion
        matrix += sum(temp_mats)
```

2023-01-03 13:01 UTC, albi3ro commented on pennylane/utils.py
> +from operator import matmul
```suggestion
```

2023-01-03 13:25 UTC, albi3ro requested changes
Thanks for opening this PR @12mB7693 !

The tests for the original `sparse_hamiltonian` method in [`test_utils.py`](https://github.com/PennyLaneAI/pennylane/blob/880517228462ba01af35d94204e55fc9c47a7cac/tests/test_utils.py#L67) can be copied and repurposed to be added to [`tests/ops/qubit/test_hamiltonian.py`](https://github.com/PennyLaneAI/pennylane/blob/master/tests/ops/qubit/test_hamiltonian.py).

We also need a changelog entry under "Deprecations". Don't forget to add your name to the list of contributors as well! The changelog can be found at: https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md

We will also need to add add entry to the [`doc/developement/deprecations.rst`](https://github.com/PennyLaneAI/pennylane/blob/880517228462ba01af35d94204e55fc9c47a7cac/doc/development/deprecations.rst) file. Since are now developing for v0.29, let's schedule `qml.utils.sparse_hamiltonian` for removal in v0.31.

I've left comments with suggestions to fix the various linting and formatting comments.  If you want to learn more about running the various tools we use to standardize code formatting, you can read [our pull request guide](https://docs.pennylane.ai/en/stable/development/guide/pullrequests.html).


We can also do this is a later PR if necessary, but we can now update the three places in PennyLane that use `qml.utils.sparse_hamiltonian`:
* https://github.com/PennyLaneAI/pennylane/blob/880517228462ba01af35d94204e55fc9c47a7cac/pennylane/devices/default_qubit.py#L590
* https://github.com/PennyLaneAI/pennylane/blob/880517228462ba01af35d94204e55fc9c47a7cac/pennylane/ops/functions/matrix.py#L125
* https://github.com/PennyLaneAI/pennylane/blob/880517228462ba01af35d94204e55fc9c47a7cac/pennylane/optimize/lie_algebra.py#L62

2023-01-16 11:33 UTC, albi3ro commented on pennylane/devices/default_qubit.py
>                      Hmat = observable.sparse_matrix()
```suggestion
                if observable.name in {"Hamiltonian", "SparseHamiltonian"}:
                     Hmat = observable.sparse_matrix()
```
An optional simplification we can now make.

2023-01-16 12:12 UTC, albi3ro reviewed
Thanks for the updates. This looks in really good shape.

I'd just like to make a comment about handling the wire order at the end with `expand_matrix`, versus constructing the sparse matrix with the wire order from the start.

Even for a simple case like:
```
H = 2.0 * qml.PauliX(0) @ qml.PauliY(1) @ qml.PauliZ(2) @ qml.PauliX(3)
%timeit qml.utils.sparse_hamiltonian(H, wires = list(reversed(H.wires)))
```

You'll see that using that handling the wire order at the end is quite a bit slower. We want to construct to the specific wire order from the very beginning.

So instead of using `self.wires` in`Hamiltonian.sparse_matrix`, we want to use `wires = wire_order or self.wires`.

Does that make sense?

2023-01-17 20:37 UTC, 12mB7693 commented
@albi3ro Thank you for reviewing what I did and for your comments, that helped me a lot.
I think I get what you mean and I will push an update soon. 
Shall I actually also update the tests, where the old function qml.utils.sparse_hamiltonian(..) is called?

2023-01-18 17:37 UTC, albi3ro commented
> @albi3ro Thank you for reviewing what I did and for your comments, that helped me a lot.
> I think I get what you mean and I will push an update soon.
> Shall I actually also update the tests, where the old function qml.utils.sparse_hamiltonian(..) is called?

Updating the tests where `qml.utils.spase_hamiltonian` is called (outside of unit tests) would be great! But I won't necessarily block approval based on that being accomplished.

2023-01-19 21:05 UTC, 12mB7693 commented
> > @albi3ro Thank you for reviewing what I did and for your comments, that helped me a lot.
> > I think I get what you mean and I will push an update soon.
> > Shall I actually also update the tests, where the old function qml.utils.sparse_hamiltonian(..) is called?
> 
> Updating the tests where `qml.utils.spase_hamiltonian` is called (outside of unit tests) would be great! But I won't necessarily block approval based on that being accomplished.

I'm not sure if I understood you correctly regarding the updates of the tests. Do you mean with "outside of unit tests" that I should not update the unit tests?

2023-01-20 12:28 UTC, albi3ro commented on pennylane/devices/default_qubit.py
>                      Hmat = observable.sparse_matrix()
Sorry this is my mistake in what I suggested:
```suggestion
                    Hmat = observable.sparse_matrix(wires=self.wires)
```

This should fix some of the failing tests.

2023-01-24 20:28 UTC, 12mB7693 commented
Not sure why the documentation check fails, I ran "make doc" locally and I get the warning
`releases/changelog-dev.md:391: WARNING: Definition list ends without a blank line; unexpected unindent.
`
However, I do not see how to fix it.

2023-01-26 18:27 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +  [(#3236)](https://github.com/PennyLaneAI/pennylane/issues/3236)
```suggestion
* `qml.utils.sparse_hamiltonian` function has been deprecated, and usage will now raise a warning.
  Instead, one should use the `~.Hamiltonian.sparse_matrix` method.
  [(#3236)](https://github.com/PennyLaneAI/pennylane/issues/3236)
```

Maybe the space was the problem?

2023-01-26 18:29 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +
```suggestion
```

2023-01-26 18:29 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +  [(#3236)](https://github.com/PennyLaneAI/pennylane/issues/3236)
```suggestion
  [(#3236)](https://github.com/PennyLaneAI/pennylane/pull/3585)
```

2023-01-26 18:30 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +  [(#3236)](https://github.com/PennyLaneAI/pennylane/issues/3236)
```suggestion
  [(#3585)](https://github.com/PennyLaneAI/pennylane/pull/3585/)
```

2023-01-26 18:30 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +  [(#3585 )](https://github.com/PennyLaneAI/pennylane/pull/3585)
```suggestion
  [(#3585)](https://github.com/PennyLaneAI/pennylane/pull/3585)
```

2023-01-26 20:14 UTC, albi3ro commented on doc/releases/changelog-dev.md
> +  [(#3585)](https://github.com/PennyLaneAI/pennylane/pull/3585/)
```suggestion
  [(#3585)](https://github.com/PennyLaneAI/pennylane/pull/3585)
```

WHY SPHINX WHY

2023-01-26 20:16 UTC, albi3ro approved these changes
Thanks @12mB7693 ! 🎉 

Looks good to me.  Glad to finally have this tidied up :)

Sphinx may still be causing some problems, but I'll try and fix then if I can.

Excellent work :)

2023-01-26 21:00 UTC, 12mB7693 commented
No problem, I'm glad that I could help. This task was definitely a good starting point as a new contributor. 
Thank you for your support @albi3ro!

2023-02-13 21:04 UTC, merged