Add function for convert circuit parameters to numpy
PennyLaneAI/pennylane pull request #3899
Opened 2023-03-14 15:01 UTC by albi3ro

Currently, we use the `qml.tape.Unwrap` context manager to convert parameters to numpy before sending them to a device.

This context manager modifies the input in-place and resets it at the end. It uses `QuantumScript.set_parameters`, which iterates over all operations, modifies them in place, and then checks batching.

Notably, it calls `op._check_batching` for every single parameter that gets set, not every operator that has parameter set.

This causes massive performance problems for large observables. We are also setting the parameters for operators that might not even need it.

This PR proposes a transform `convert_to_numpy_parameters` that creates a new quantum script with numpy or built-ins parameters.  Currently, it is in the `devices.preprocessing` module, as it was designed thinking about new devices, and making it easy for new devices to convert to vanilla numpy parameters.

Given the huge performance problems with `Unwrap`, we should consider using this everywhere instead.

![Screenshot 2023-03-14 at 10 48 22 AM](https://user-images.githubusercontent.com/6364575/225042785-b5a0541d-4979-4609-b012-9be084b25241.png)

2023-04-05 15:04 UTC, timmysilv approved these changes

2023-04-05 15:05 UTC, timmysilv requested changes

2023-04-05 15:05 UTC, timmysilv commented on pennylane/transforms/convert_to_numpy_parameters.py
> +    return qml.tape.QuantumScript(new_ops, new_meausurements, new_prep)
```suggestion
    return circuit.__class__(new_ops, new_meausurements, new_prep)
```

2023-04-10 14:04 UTC, timmysilv commented
it's as if you magically looked at my local branch and nabbed the changes I made! looks excellent. I want to confirm a thing or two before approving, but I will likely approve today.

2023-04-10 15:25 UTC, mudit2812 approved these changes
Thanks Christina! I think that this looks good. Is there a timeline for when this would replace `tape.unwrap`?

2023-04-10 21:06 UTC, timmysilv commented on pennylane/transforms/convert_to_numpy_parameters.py
> +    See also :class:`pennylane.tape.Unwrap`.  ``convert_to_numpy_parameters`` function creates a new :class:`pennylane.tape.QuantumScript`
can we use the Sphinx seealso directive here? The formatting in the docs look a little busy here imo

2023-04-11 13:41 UTC, timmysilv commented on pennylane/transforms/convert_to_numpy_parameters.py
> +    copied_m.obs.data = math.unwrap(m.obs.data)
```suggestion
    copied_m.obs.data = math.unwrap(
        [o.data for o in m.obs.obs]
        if isinstance(copied_m.obs, qml.operation.Tensor)
        else m.obs.data
    )
```

2023-04-11 16:00 UTC, albi3ro commented
> Thanks Christina! I think that this looks good. Is there a timeline for when this would replace `tape.unwrap`?

@mudit2812  We are working on a PR to replace the use of `unwrap` in the interfaces module.

2023-04-11 17:08 UTC, timmysilv commented on pennylane/transforms/convert_to_numpy_parameters.py
> +        :class:`pennylane.tape.Unwrap` modifies a :class:`qml.tape.QuantumScript` in place instead of creating
```suggestion
        :class:`pennylane.tape.Unwrap` modifies a :class:`~.pennylane.tape.QuantumScript` in place instead of creating
```

2023-04-12 04:01 UTC, timmysilv approved these changes

2023-04-12 18:26 UTC, merged