Additions to BlockEncode and TensorFlow support
PennyLaneAI/pennylane pull request #3905
Opened 2023-03-15 15:03 UTC by DSGuala

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-04-05 13:34 UTC, Jaybsoni commented
The current version does not have support for Tensorflow and only partial support for jax. This will be added to the operation afterwards.

2023-04-06 21:13 UTC, soranjh reviewed
Looks good to me, left few questions and comments.

2023-04-06 21:13 UTC, soranjh commented on tests/math/test_multi_dispatch.py
> +#     ]
Why this is here?

2023-04-06 21:13 UTC, soranjh commented on tests/ops/qubit/test_matrix_ops.py
> +                f"Block encoding a \({2} x {2}\) matrix requires a hilbert space of size"
```suggestion
                f"Block encoding a \({2} x {2}\) matrix requires a Hilbert space of size"
```

2023-04-06 21:13 UTC, soranjh commented on tests/ops/qubit/test_matrix_ops.py
> +        ],
Should this be defined for each interface separately? I suppose the tests for different interfaces use the same data?

2023-04-06 21:13 UTC, soranjh approved these changes

2023-04-06 21:20 UTC, obliviateandsurrender requested changes
Leaving a few suggestions

2023-04-06 21:20 UTC, obliviateandsurrender commented on pennylane/math/multi_dispatch.py
> +def norm(tensor, like=None, **kwargs):
It possibly requires a docstring.

2023-04-06 21:20 UTC, obliviateandsurrender commented on pennylane/ops/qubit/matrix_ops.py
> +    def adjoint(self):
Does this require unit-tests?

2023-04-06 21:20 UTC, obliviateandsurrender commented on pennylane/ops/qubit/matrix_ops.py
> +    def label(self, decimals=None, base_label=None, cache=None):
Does this require unit-tests?

2023-04-06 21:20 UTC, obliviateandsurrender commented on tests/math/test_multi_dispatch.py
> +# @pytest.mark.all_interfaces
Please remove commented code.

2023-04-06 21:20 UTC, obliviateandsurrender commented on tests/ops/qubit/test_matrix_ops.py
> +    def test_correct_error_message(self, input_matrix, wires, msg):
Docstring is missing for the test.

2023-04-06 21:20 UTC, obliviateandsurrender commented on tests/ops/qubit/test_matrix_ops.py
> +    def test_adjoint(self, input_matrix, wires):
Docstring is missing for the test.

2023-04-06 21:20 UTC, obliviateandsurrender commented on tests/ops/qubit/test_matrix_ops.py
> +    def test_blockencode_grad_tf(self, wires, input_matrix, expected_result):
Docstring is missing for the test.

2023-04-10 13:58 UTC, Jaybsoni commented on tests/math/test_multi_dispatch.py
> +#     ]
Missing test was since added

2023-04-10 14:02 UTC, Jaybsoni commented on tests/math/test_multi_dispatch.py
> +# @pytest.mark.all_interfaces
Missing test was added

2023-04-10 14:09 UTC, Jaybsoni commented on pennylane/ops/qubit/matrix_ops.py
> +    def label(self, decimals=None, base_label=None, cache=None):
We should be fine for now 👍🏼

2023-04-10 16:26 UTC, merged