Take wire ordering in the `wires` argument to `qml.density_matrix` into account
PennyLaneAI/pennylane pull request #4072
Opened 2023-05-02 06:46 UTC by dwierichs

**Context:**
#878 added the functionality to return reduced density matrices by introducing `qml.density_matrix(wires=...)` as a return object in a QNode. While the reduction by tracing out the correct wires is respected, the _ordering_ of the given wires is not taken into account.
The following code therefore produces the same result for `wires=[0, 1]` and `wires=[1, 0]`, although it should differ:
```python
import pennylane as qml

wires = [0, 1]
#wires = [1, 0]
dev = qml.device("default.qubit", wires=2)
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    return qml.density_matrix(wires=wires)

circuit()
```

**Description of the Change:**
This PR takes the wire ordering into account as well by applying `pennylane.math.matrix_manipulation.py::_permute_dense_matrix` to the computed density matrix in `pennylane.math.quantum.py::reduced_dm`. 

In addition, this PR raises an error when broadcasting is detected in `reduced_dm`, because this is not supported and currently crashes in some cases somewhat incomprehensibly.

**Benefits:**
Bug fix of the above. Transparency of broadcasting scenario that is not supported anyways.

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-05-09 14:29 UTC, mudit2812 requested changes
Thanks for the changes @dwierichs and for the rigorous testing. I have concerns about the condition that checks for broadcasting, but other than that, this looks good!

2023-05-11 17:26 UTC, dwierichs commented on pennylane/math/quantum.py
> +    if (len(shape) == 2 and shape[0] != shape[1]) or len(shape) == 3:
I agree, this is not very nice. However, it is an existing bug, not a new one...

I'd suggest that we actually pass the information of whether the input is a density matrix or a state vector to `reduced_dm` (the device using the function will know!).
Then we can make proper decisions and don't have an "almost always right guess" :)

2023-05-11 17:59 UTC, dwierichs commented on pennylane/math/quantum.py
> +    if (len(shape) == 2 and shape[0] != shape[1]) or len(shape) == 3:
@mudit2812 I suggested something in the code, what do you think? :) 
The disadvantage is, that the default qubit and mixed devices now have to copy the `density_matrix` code of `QubitDevice` :/

2023-05-15 16:01 UTC, mudit2812 approved these changes
I'm happy to approve this PR in it's current state. One way of avoiding overriding `QubitDevice.density_matrix` is to check what type of device is being used in `QubitDevice.density_matrix` itself:

```python
input_is_dm = self.short_name[-5:] == "mixed"
return qml.math.reduced_dm(state, indices=wires, c_dtype=self.C_DTYPE, input_is_dm=input_is_dm)
```

I'm hopeful this change wouldn't interfere with plugins as I'm not sure if any of the plugin devices support state measurements, but it's probably something that should be checked before my suggested change is potentially implemented.

2023-05-17 19:19 UTC, eddddddy commented on pennylane/math/quantum.py
> +    if (len(shape) == 2 and shape[0] != shape[1]) or len(shape) == 3:
I think it's fine to leave it. I'll split the logic for state vectors and density matrices in a follow-up PR when I address broadcasting. For this PR we can just focus on the wire ordering part.

2023-05-18 14:23 UTC, albi3ro commented on tests/measurements/test_state.py
Can we get some unit tests for `StateMP.proces_state`? This will be important for making sure it works with the new device, and not just the old one.

2023-05-19 07:56 UTC, dwierichs commented on tests/measurements/test_state.py
It seems that `process_state` returns a matrix or a vector based on whether the MP has wires. Is this a decision we want to maintain? It seems like a similarly indirect inference of code behaviour as for `reduced_dm`.

2023-05-19 08:06 UTC, dwierichs commented on tests/measurements/test_state.py
Also, `wire_order` is an unused `kwarg` in the state vector case. This is not harmful, I guess, because we do not really expose `process_state`, but I think we should have `process_state` return a permuted state vector if `wire_order` is provided. Should I change this?

2023-05-19 14:33 UTC, eddddddy approved these changes
Thanks for separating out the broadcasting logic! Happy to approve now, but this is conditional on @albi3ro's comment being addressed.

2023-05-20 12:50 UTC, dwierichs commented
@albi3ro , could you check whether I understood you correctly and implemented the checks you were thinking of? :) 

Thanks @eddddddy for the quick reviews and discussions!

2023-05-24 14:25 UTC, albi3ro approved these changes
Looks good to me, and can be merged as is.

2023-05-24 14:35 UTC, albi3ro commented on tests/measurements/test_state.py
I know I just approved, but in the `density_matrix` case, I think we do need to use the `wire_order`.  What if the device has non-standard indices?

2023-05-25 16:01 UTC, eddddddy commented on tests/measurements/test_state.py
The issue with `process_state` when passed a state vector can be addressed in a later PR.

2023-05-25 16:58 UTC, merged