Fixed Float point errors in Hamiltonian.compare function
PennyLaneAI/pennylane pull request #4597
Opened 2023-09-14 20:25 UTC by dubeyPraY

**Context:** Comparing Hamiltonian float point error

**Description of the Change:** Rounding off the Hamiltonian to the 15th digit to remove float point error in `hamiltonian.compare`

**Benefits:** Removes Float point error

**Possible Drawbacks:**

**Related GitHub Issues:** Fixed #4567

2023-09-14 20:29 UTC, dubeyPraY commented
@CatalinaAlbornoz I reworked it. Please have a look at it. 
@mudit2812 I have iterated through the set and compared each value to each value of the other set Hamiltonian. This shall fix the issue we were having with sets. Thank you

2023-09-14 21:17 UTC, mudit2812 requested changes
Thanks @dubeyPraY for the PR. The solution looks much better! I left a few suggestions. Please run `black` and `pylint` on the files you have updated to format and factor the code. You can find out how to use them in the PennyLane guide for [submitting pull requests](https://docs.pennylane.ai/en/stable/development/guide/pullrequests.html#continuous-integration-checks).

I'll be happy to approve once the requested changes are addressed and all continuous integration tests pass.

2023-09-14 21:17 UTC, mudit2812 commented on pennylane/ops/qubit/hamiltonian.py
> +                        Continue
```suggestion
                        continue
```

2023-09-14 21:17 UTC, mudit2812 commented on pennylane/ops/qubit/hamiltonian.py
> +                    if (round(selfdata[0],15),selfdata[1])== (round(otherdata[0],15),otherdata[1]):#to remove floatt point error
We can just use numpy here

```suggestion
                    if np.isclose(selfdata[0], otherdata[0]):
```

2023-09-14 21:17 UTC, mudit2812 commented on pennylane/ops/qubit/hamiltonian.py
> +                flag = False
A slightly more descriptive name for this boolean would probably be more appropriate, maybe something like `is_equal`?

2023-09-14 21:17 UTC, mudit2812 commented on tests/hamiltonian_compare.py
No need to make a new file for one test. You can move this test to `tests/ops/qubit/test_hamiltonian.py` inside the `TestHamiltonian` class.

2023-09-14 21:17 UTC, mudit2812 commented on tests/hamiltonian_compare.py
> +def test_hamiltonian_compare():
Please include a doc string with the test with a description of the test. You can take a look at the other test files for an example.

2023-09-14 21:17 UTC, mudit2812 commented on pennylane/ops/qubit/hamiltonian.py
> +            for selfdata in self._obs_data():
Pythonic formatting for variable names uses an underscore between individual words.
 
```suggestion
            for self_data in self._obs_data():
```

2023-09-14 21:17 UTC, mudit2812 commented on pennylane/ops/qubit/hamiltonian.py
> +                for otherdata in other._obs_data():
See above
```suggestion
                for other_data in other._obs_data():
```

2023-09-14 21:17 UTC, mudit2812 commented on doc/releases/changelog-dev.md
> +Yash Prabhat,
The names must be ordered alphabetically with respect to your last name, so it should be earlier in the list

2023-09-15 06:04 UTC, dubeyPraY commented
@mudit2812 Thank you for your response. I was actually having some issues with black. It's changing all the `2**a` to `2** a` thus formatting 192 files. I am not sure if that's the result you were hoping. For the rest changes, I shall do them if time allows and create a PR. Thank you.

2023-09-15 10:37 UTC, closed without merging