implement map_wires for cond and measurementValue
PennyLaneAI/pennylane pull request #4884
Opened 2023-11-24 21:49 UTC by timmysilv

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-11-27 21:17 UTC, mudit2812 requested changes
Thanks Matt! `MeasurementProcess.map_wires` also needs to be updated as it currently [maps wires for measurement values manually](https://github.com/PennyLaneAI/pennylane/blob/b77f67447541f2a816fe38e383536d3edb84edd7/pennylane/measurements/measurements.py#L473). And since this change was motivated by custom labels on the MPL drawer, maybe a test for that would be a good idea as well. Otherwise happy to approve!

2023-11-27 21:38 UTC, albi3ro reviewed
Once mudit's comments are resolved I'll approve.

2023-11-28 18:13 UTC, albi3ro approved these changes

2023-11-28 21:36 UTC, mudit2812 approved these changes

2023-11-28 22:01 UTC, merged