Add a note for  to `qml.eigvals`
PennyLaneAI/pennylane pull request #5095
Opened 2024-01-23 16:58 UTC by obliviateandsurrender

**Context:** The second-quantized molecular Hamiltonian's eigenspectrum contains energies corresponding to charged species in addition to the neutral one. Therefore, the smallest eigenvalue might not always give the correct ground state energy.

**Description of the Change:** Adds this to the note in `qml.eigvals` 

**Benefits:** Clears confusion regarding eigenspectrum for the charged species.

**Possible Drawbacks:** N/A

**Related GitHub Issues:** #5016

2024-01-24 21:26 UTC, soranjh requested changes

2024-01-24 21:26 UTC, soranjh commented on pennylane/ops/functions/eigvals.py
> +          always have the correct particle number and correspond to the correct ground state energy.
A second-quantized :mod:`molecular Hamiltonian <pennylane.qchem.molecular_hamiltonian>` is independent of the number of electrons and its eigenspectrum contains the energies of the neutral and charged molecules. Therefore, the `smallest` eigenvalue returned by ``qml.eigvals`` for a molecular Hamiltonian might not always correspond to the neutral molecule.

2024-01-24 22:57 UTC, soranjh approved these changes

2024-01-29 18:02 UTC, isaacdevlugt approved these changes

2024-01-29 22:59 UTC, merged