[wip] add direct call to pyscf in qchem
PennyLaneAI/pennylane pull request #5118
Opened 2024-01-29 18:54 UTC by soranjh

**Context:**
The 'pyscf' backend in qchem currently runs 'OpenFermion-PySCF' to compute molecular integrals, with PySCF, and use the integrals to construct a qubit Hamiltonian with `OpenFermion`. With the new support for fermionic operations in PennyLane, qchem can directly run PySCF when the 'pyscf' blackened is selected. 

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2024-01-29 18:55 UTC, soranjh commented
[sc-52875]

2024-02-20 14:42 UTC, obliviateandsurrender requested changes
Thanks @soranjh, looks good. Just left some initial feedback.

2024-02-20 14:42 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +            h_pl = qml.jordan_wigner(hf)
We don't have to simplify it in this case or discard close-to-zero imaginary coefficients?

2024-02-20 14:42 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +    r"""Compute pyscf integrals."""
It might be worthwhile to document or have code comments on the steps in the integral computation.

2024-02-20 14:42 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +    one_mo = np.einsum("pi,pq,qj->ij", molhf.mo_coeff, one_ao, molhf.mo_coeff)
Based on the benchmarking done, do you think [this](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html) requires `optimize=True`?

2024-02-20 18:01 UTC, iloaiza requested changes
One-electron integrals in active space are not calculated correctly right now, some indices are missing in the code (marked in the comment). Everything else is looking good.

2024-02-21 17:58 UTC, iloaiza approved these changes
Looking good!

2024-02-22 12:15 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +    if wires:
If we define `wire_map` as `None` here then we would need just one `if-else` block at line `990`.

2024-02-22 18:28 UTC, trbromley commented
@soranjh, would you mind adding an entry to the changelog?

2024-03-04 16:26 UTC, merged