empty commit
PennyLaneAI/pennylane pull request #5415
Opened 2024-03-19 19:26 UTC by PietropaoloFrisoni

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2024-03-20 14:16 UTC, PietropaoloFrisoni commented on pennylane/ops/op_math/pow.py
This `qml.simplify` is due to the following behavior:

```
>>> #self.base.generator() = -0.5 * X(0)
>>> #self.z = 2.5
>>> qml.Hamiltonian([2.5], [-0.5 * qml.X(0)]), qml.simplify(qml.Hamiltonian([2.5], [-0.5 * qml.X(0)]))
(2.5 * -0.5 * X(0), -1.25 * X(0))
```
If we call `qml.generator` as follows (without the `qml.simplify` here):
```
>>> z = 2.5
>>> base = qml.RX(2.34, wires=0)
>>> op = Pow(base, z)
>>> qml.generator(op, format="prefactor")
(-0.5 * X(0), 2.5)
```
That is, the `qml.generator(op, format="prefactor")` function requires the function to be simplified not to have bugs.

2024-03-20 17:26 UTC, PietropaoloFrisoni commented on tests/ops/op_math/test_adjoint.py
This is just to remark on the difference since `test_generator_legacy` would work even with opmath enabled (but `test_generator` does not work with opmath disabled) after the last modification to the source code. Probably it is best to eliminate the second one and remove the `@pytest.mark.usefixtures("use_legacy_opmath")` from the former

2024-03-20 17:32 UTC, PietropaoloFrisoni commented on pennylane/ops/op_math/pow.py
As for `adjoint.py`, here this extra line is only necessary when 
- opmath is **disabled**. That is, to avoid situations like:

```
>>> qml.Hamiltonian([-1.0], [op.generator()])
(-1.0) [Hamiltonian0]
```

- when opmath is **enabled**, but we don't simplify:


```
>>> qml.Hamiltonian([-1.0], [op.generator()])
-1.0 * 0.5 * X(0)
```

2024-03-20 18:58 UTC, lillian542 commented on pennylane/ops/op_math/adjoint.py
> +        return qml.Hamiltonian([-1.0 * base_gen.coeffs[0]], base_gen.ops)
I can see this used to be `-1 * self.base.generator()`, and then the `s_prod` above. What has changed so the we need to separate out the `base_gen.coeffs` now?

2024-03-20 18:59 UTC, lillian542 commented on pennylane/ops/op_math/adjoint.py
> +        return qml.Hamiltonian([-1.0 * base_gen.coeffs[0]], base_gen.ops)
And what happens here if the `base_gen` is a `Sum`, for example? By unpacking `base_gen.ops`, but still only having a single coefficient, the length of coifs and base_gen won't match, and we'll get an error.

2024-03-20 19:08 UTC, lillian542 commented on pennylane/ops/op_math/pow.py
Ah, I see - but this is broken if your base Hamiltonian has more than one term. Better to end up with something that could be simplified further than something that raises an error. Possibly best to just restore this to `-1 * base_gen`. Then it will return a `Hamiltonian` with legacy opmath and an `SProd` with new opmath. 

It doesn't follow the "things that are Hamiltonians with legacy functionality are LinearCombinations now" convention, but we're following that a lot more loosely than "if new_opmath is enabled, you should get an arithmetic operator, and if old opmath is enabled, a legacy operator".

2024-03-20 19:09 UTC, lillian542 commented on pennylane/ops/op_math/pow.py
> +        return qml.Hamiltonian([self.z * base_gen.coeffs[0]], base_gen.ops)
same issue

2024-03-20 19:35 UTC, lillian542 commented on pennylane/ops/qubit/parametric_ops_multi_qubit.py
> +            ],
Not sure why this one is an issue and everything else is fine, but this seems to break `parameter_frequencies` (and thereby adjoint differentiation) for `IsingXY`. 

To make sure we preserve functionality, let's add the `use_legacy_and_new_opmath` fixture to the parameter frequency test as well (getting parameter frequencies is one of the main uses for the generators). And then debug why this particular operator is failing 😅

2024-03-20 22:56 UTC, PietropaoloFrisoni commented on pennylane/ops/op_math/adjoint.py
The reason why we are not simply returning `qml.Hamiltonian([-1.0], [base.generator()])` is that, with opmath **disabled**, we have the following behavior that causes problems in many tests:
```
>>> qml.Hamiltonian([-1.0], [base.generator()])
(-1.0) [Hamiltonian0]
```

2024-03-20 23:02 UTC, PietropaoloFrisoni commented on pennylane/ops/op_math/pow.py
The reason why we are not simply returning `qml.Hamiltonian([self.z], [self.base.generator()])` is the same explained for the file `pennylane/ops/op_math/adjoint.py` (see comment above)

2024-03-21 11:17 UTC, Qottmann commented on pennylane/ops/op_math/pow.py
Note that for LinearCombination class a scalar multiplication is eager:
```
>>> 0.5 * qml.ops.LinearCombination([0.5], [X(0)])
0.25 * X(0)
```

Doesnt that simplify the problem?

2024-03-21 11:21 UTC, Qottmann requested changes
I think we can have best of both worlds with the suggestion. Else looks great 👍 Happy to approve with that fixed :)

2024-03-21 13:47 UTC, lillian542 commented on pennylane/ops/op_math/pow.py
Not all generators are `LinearCombinations`, but definitely makes it more of an edge case. What is missing should be handled elsewhere, not here. It shouldn't be a problem that things are `SProd` of `Sum` for example (IMO).

2024-03-21 13:49 UTC, lillian542 commented on tests/ops/op_math/test_adjoint.py
> +        """Assert that the generator of an Adjoint is -1.0 times the base generator with opmath disabled."""
Doesn't this version work for both now?

2024-03-21 13:50 UTC, lillian542 approved these changes
I think one pair of `legacy` and `new` tests can be combined now, but no blocking comments. Looks good to me, glad this is resolved! 🚀

2024-03-21 14:05 UTC, Qottmann commented on pennylane/ops/op_math/pow.py
yep sounds good 👍

2024-03-21 14:06 UTC, Qottmann approved these changes
nice 👌

2024-03-21 15:07 UTC, merged