Bugfix/mcm key dtype
PennyLaneAI/pennylane pull request #5587
Opened 2024-04-29 14:41 UTC by vincentmr

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2024-04-29 15:10 UTC, dwierichs requested changes
Thanks for the quick fix, @vincentmr 
Could you add a test for the fix, maybe just the case from the issue? :)

2024-04-29 15:10 UTC, dwierichs commented on pennylane/transforms/dynamic_one_shot.py
> +    mcm_samples = np.array(mcm_samples).reshape((-1, 1))
Could we do
```suggestion
    mcm_samples = np.array(mcm_samples).reshape((len(samples), 1))
```
because we know the shape?

2024-04-29 15:10 UTC, dwierichs commented on pennylane/transforms/dynamic_one_shot.py
> +        keys = np.array(list(new_measurement.keys())).astype(mcm_samples.dtype)
Nice :100:

2024-04-29 16:23 UTC, dwierichs approved these changes
Thanks @vincentmr !

2024-04-29 17:56 UTC, mudit2812 approved these changes

2024-04-30 13:15 UTC, merged

2024-04-30 16:01 UTC, vincentmr commented
[sc-61845]