Fix `qml.draw/_mpl` to work with deferred measurements circuits that use MCMs in measurements
PennyLaneAI/pennylane pull request #5610
Opened 2024-04-30 21:25 UTC by mudit2812

**Context:**
`defer_measurements` leaves `MeasurementValue`s in the terminal measurement processes if they are present. This is not friendly with the drawer as the classical wires for those measurement values do not exist when using `defer_measurements`. This PR adds a "hack" fix so that the drawer/MPL drawer work with this scenario.

**Description of the Change:**
Add `transform_deferred_measurements_tape` util function, which replaces any `MeasurementValue`s present in the tape after applying `defer_measurements` with wires. This transform is only applied in `tape_text` and `tape_mpl`.

**Benefits:**
Drawer works better with MCMs

**Possible Drawbacks:**
Hacky fix, technical debt to implement cleaner fix later

**Related GitHub Issues:**
https://github.com/PennyLaneAI/pennylane/issues/5588

2024-04-30 21:28 UTC, mudit2812 commented on doc/releases/changelog-0.36.0.md
> +  [(#)]()
```suggestion
  [(#5610)](https://github.com/PennyLaneAI/pennylane/pull/5610)
```

2024-05-01 14:08 UTC, mudit2812 commented
[sc-62204]

2024-05-01 14:58 UTC, dwierichs requested changes
Nice, thanks for the quick fix @mudit2812 :)
Just one suggestion to cover the uncovered line within a test you added.

2024-05-01 14:58 UTC, dwierichs commented on tests/transforms/test_defer_measurements.py
> +            return mp(op=m_0)
To cover the uncovered test line, can do
```suggestion
            return mp(op=m_0), qml.expval(qml.Z(1))
```

2024-05-01 15:17 UTC, dwierichs approved these changes
Thanks!

2024-05-01 21:16 UTC, merged