Support Angstrom units with Molecule class and molecular_hamiltonian function
PennyLaneAI/pennylane pull request #5694
Opened 2024-05-16 13:21 UTC by ddhawan11

**Context:**
Support Angstrom units along with Bohr

**Description of the Change:**
Molecule class and molecular_hamiltonian function now works with both Bohr and Angstrom units.

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2024-05-16 13:39 UTC, ddhawan11 commented
[sc-62838]

2024-05-16 15:46 UTC, austingmhuang reviewed
Looks good @ddhawan11.

Maybe I missed it (or it already exists) but is there some kind of warning or error that will pop up when a user inputs a unit that doesn't exist?

For example, let's say they put a typo and wrote angstorm instead of angstrom.
`molecule_ang = qchem.molecular_hamiltonian(symbols, geometry_ang, unit="Angstorm")`.

Would this raise a warning and let them know 'Bohr' was used instead?

2024-05-16 16:02 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +    if unit == "Angstrom":
We should add an `if` condition for inconsistent unit values.

2024-05-17 14:18 UTC, obliviateandsurrender commented on pennylane/qchem/molecule.py
> +        elif unit not in ("Angstrom", "Bohr"):
We should always aim to fail early, i.e., we should shift this right under the checks done above for atoms and basis set.

2024-05-21 14:24 UTC, austingmhuang reviewed
Looks great @ddhawan11! Just some small changes but otherwise should be good to go soon.

2024-05-21 14:24 UTC, austingmhuang commented on pennylane/qchem/molecule.py
> +
The string comparison here is case-sensitive. We should make this case insensitive 😄

2024-05-21 14:24 UTC, austingmhuang commented on pennylane/qchem/molecule.py
> +            )
```suggestion
        if self.unit not in ("angstrom", "bohr"):
            raise ValueError(
                f"The provided unit, '{unit}' is not supported. "
                f"Please set 'unit' to 'Bohr' or 'Angstrom'."
            )
            
        if self.unit == "angstrom":
            self.coordinates = self.coordinates / bohr_angs
```

We should raise errors early.

2024-05-21 14:24 UTC, austingmhuang commented on pennylane/qchem/openfermion_obs.py
> +
```suggestion
    if unit not in ("angstrom", "bohr"):
        raise ValueError(
            f"The provided unit, '{unit}' is not supported. "
            f"Please set 'unit' to 'Bohr' or 'Angstrom'."
        )
        
    if unit == "angstrom":
        coordinates = coordinates / bohr_angs

```

Should make this not case sensitive either.

2024-05-21 15:58 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +    if unit not in ("angstrom", "bohr"):
```suggestion
    if unit.lower() not in ("angstrom", "bohr"):
```

2024-05-21 17:40 UTC, austingmhuang approved these changes
Looks good to me! Nice work @ddhawan11 :)

2024-05-21 18:23 UTC, obliviateandsurrender requested changes
Just a couple of more changes, and should be good to go! 🚀

2024-05-21 18:23 UTC, obliviateandsurrender commented on pennylane/qchem/openfermion_obs.py
> +        coordinates = coordinates / bohr_angs
```suggestion
    if (coord_unit := unit.strip().lower()) not in ("angstrom", "bohr"):
        raise ValueError(
            f"The provided unit, '{unit}' is not supported. "
            f"Please set 'unit' to 'Bohr' or 'Angstrom'."
        )

    if coord_unit == "angstrom":
        coordinates = coordinates / bohr_angs
```
We might want to repeat the stripping.

2024-05-21 18:23 UTC, obliviateandsurrender commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    assert qml.ops.functions.equal(hamiltonian_ang, hamiltonian_bohr)
Could we not use `qml.equal` directly here, or is this some other function? 🤔

2024-05-21 18:23 UTC, obliviateandsurrender commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    method = "pyscf"
```suggestion
```
Isn't this overriding the parameterized `method`?

2024-05-21 18:23 UTC, obliviateandsurrender commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    assert qml.ops.functions.equal(hamiltonian_ang, hamiltonian_bohr)
Same as above.

2024-05-22 12:47 UTC, ddhawan11 commented on doc/releases/changelog-dev.md
> +* `qml.qchem.Molecule` and qchem functions that take Molecule object as an argument now work with coordinates
This is just a placeholder for now, we will be creating one change-log entry for all of the qchem feature branch.

2024-05-22 13:40 UTC, obliviateandsurrender approved these changes
Good work @ddhawan11, LGTM!

2024-05-22 18:01 UTC, soranjh commented on pennylane/qchem/molecule.py
> +        unit="Bohr",
```suggestion
        unit="bohr",
```

2024-05-22 18:02 UTC, soranjh commented on pennylane/qchem/molecule.py
> +                f"Please set 'unit' to 'Bohr' or 'Angstrom'."
```suggestion
                f"The provided unit '{unit}' is not supported. "
                f"Please set 'unit' to 'bohr' or 'angstrom'."
```

2024-05-22 18:03 UTC, soranjh commented on pennylane/qchem/openfermion_obs.py
> +    unit="Bohr",
```suggestion
    unit="bohr",
```

2024-05-22 18:04 UTC, soranjh commented on pennylane/qchem/openfermion_obs.py
> +            f"Please set 'unit' to 'Bohr' or 'Angstrom'."
```suggestion
            f"The provided unit '{unit}' is not supported. "
            f"Please set 'unit' to 'bohr' or 'angstrom'."
```

2024-05-22 18:05 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +        unit="Bohr",
```suggestion
        unit="bohr",
```

2024-05-22 18:05 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +        unit="Angstrom",
```suggestion
        unit="angstrom",
```

2024-05-22 18:06 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    molecule_bohr = qchem.Molecule(symbols, geometry_bohr, unit="Bohr")
```suggestion
    molecule_bohr = qchem.Molecule(symbols, geometry_bohr, unit="bohr")
```

2024-05-22 18:06 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    molecule_ang = qchem.Molecule(symbols, geometry_ang, unit="Angstrom")
```suggestion
    molecule_ang = qchem.Molecule(symbols, geometry_ang, unit="angstrom")
```

2024-05-22 18:07 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    r"""Test that an error is raised if a wrong/not-supported units for coordinates are entered."""
```suggestion
    r"""Test that an error is raised if a wrong/not-supported unit for coordinates is entered."""
```

2024-05-22 18:07 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    with pytest.raises(ValueError, match="The provided unit, 'degrees' is not supported."):
```suggestion
    with pytest.raises(ValueError, match="The provided unit 'degrees' is not supported."):
```

2024-05-22 18:08 UTC, soranjh commented on tests/qchem/test_molecule.py
> +        r"""Test that an error is raised if a wrong/not-supported units for coordinates are entered."""
```suggestion
        r"""Test that an error is raised if a wrong/not-supported unit for coordinates is entered."""
```

2024-05-22 18:08 UTC, soranjh commented on tests/qchem/test_molecule.py
> +        with pytest.raises(ValueError, match="The provided unit, 'degrees' is not supported."):
```suggestion
        with pytest.raises(ValueError, match="The provided unit 'degrees' is not supported."):
```

2024-05-23 17:51 UTC, soranjh approved these changes

2024-05-23 17:51 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    """
```suggestion
def test_coordinate_units_for_molecular_hamiltonian(method, tmpdir):
    r"""Test that molecular_hamiltonian generates the Hamiltonian for both Bohr and Angstrom units.
    """
```

2024-05-23 17:51 UTC, soranjh commented on tests/qchem/of_tests/test_molecular_hamiltonian.py
> +    based on user defined information.
```suggestion
def test_coordinate_units_for_molecular_hamiltonian_molecule_class(method, tmpdir):
    r"""Test that molecular_hamiltonian generates the Hamiltonian for both Bohr and Angstrom units.
```

2024-05-23 18:59 UTC, ddhawan11 commented
[sc-62838]

2024-05-24 13:14 UTC, trbromley commented on doc/releases/changelog-dev.md
> +
```suggestion
```

2024-05-24 13:14 UTC, trbromley commented on doc/releases/changelog-dev.md
> +
```suggestion
```

2024-05-24 13:14 UTC, trbromley commented on doc/releases/changelog-dev.md
> +* `qml.qchem.Molecule` and qchem functions that take Molecule object as an argument now work with coordinates
```suggestion
* `qml.qchem.Molecule` and qchem functions that take `Molecule` object as an argument now work with coordinates
```

2024-05-24 14:06 UTC, merged