fixed typehints syntax errors and old typing style
PennyLaneAI/pennylane pull request #5964
Opened 2024-07-08 15:52 UTC by Shiro-Raven

**Context:**
Some type hints were written incorrectly and went undetected since no type validation tools are used.

**Description of the Change:**
- Added new type `TapeBatch` and `PostprocessingFn` to the `qml.typing` module for use in type hints of transforms.
- Fixed all syntactical mistakes in existing type hints and adopted the new types.
- Replaced pre-python 3.9 instances of `typing.List`, `typing.Tuple`, and `typing.Dict` with built-in types `tuple`, `list` and `dict`

[[sc-63422](https://app.shortcut.com/xanaduai/story/63422)]

2024-07-08 16:36 UTC, albi3ro commented on pennylane/transforms/core/transform_program.py
> +    def __call__(self, tapes: tuple[QuantumTape]) -> tuple[ResultBatch, BatchPostProcessingFn]:
```suggestion
    def __call__(self, tapes: TapeBatch) -> tuple[TapeBatch, BatchPostProcessingFn]:
```

2024-07-08 16:41 UTC, albi3ro commented on pennylane/workflow/construct_batch.py
> +    def batch_constructor(*args, **kwargs) -> tuple[tuple["qml.tape.QuantumTape", Callable]]:
```suggestion
    def batch_constructor(*args, **kwargs) -> tuple[BatchTape, Callable]]:
```

2024-07-08 16:44 UTC, albi3ro commented on pennylane/workflow/jacobian_products.py
> +        self, tapes: Batch, tangents: tuple[Sequence[TensorLike]]
```suggestion
        self, tapes: TapeBatch, tangents: tuple[Sequence[TensorLike]]
```

2024-07-08 16:44 UTC, albi3ro commented on pennylane/workflow/jacobian_products.py
> +Batch = tuple[QuantumScript]
Can probably just use `qml.typing.TapeBatch`.

2024-07-08 16:45 UTC, albi3ro commented on pennylane/workflow/jacobian_products.py
> +    def compute_jacobian(self, tapes: Batch) -> tuple:
```suggestion
    def compute_jacobian(self, tapes: TapeBatch) -> tuple:
```

so on and so forth.

2024-07-08 16:45 UTC, albi3ro commented on pennylane/workflow/jacobian_products.py
> +    def execute_and_compute_jacobian(self, tapes: Batch) -> tuple:
```suggestion
    def execute_and_compute_jacobian(self, tapes: Batch) -> tuple[ResultBatch, tuple]:
```

2024-07-10 15:34 UTC, albi3ro requested changes
So I just checked the branch out, and now running `import pennylane as qml` gives me an error.

Selection of the traceback is:
```
File [~/Prog/pennylane/pennylane/transforms/optimization/remove_barrier.py:22](http://localhost:8888/~/Prog/pennylane/pennylane/transforms/optimization/remove_barrier.py#line=21)
     18 from pennylane.transforms import transform
     19 from pennylane.typing import PostprocessingFn, TapeBatch
---> 22 @transform
     23 def remove_barrier(tape: QuantumTape) -> tuple[TapeBatch, PostprocessingFn]:
     24     """Quantum transform to remove Barrier gates.
     25 
     26     Args:
   (...)
     79 
     80     """
     81     operations = filter(lambda op: op.name != "Barrier", tape.operations)

File [~/Prog/pennylane/pennylane/transforms/core/transform.py:218](http://localhost:8888/~/Prog/pennylane/pennylane/transforms/core/transform.py#line=217), in transform(quantum_transform, expand_transform, classical_cotransform, is_informative, final_transform, use_argnum_in_expand)
    212 if not callable(quantum_transform):
    213     raise TransformError(
    214         f"The function to register, {quantum_transform}, "
    215         "does not appear to be a valid Python function or callable."
    216     )
--> 218 signature_transform = get_type_hints(quantum_transform)
    220 # 2: Checks for the expand transform
    221 if expand_transform is not None:
```

I work with Python 3.11 locally. Tagging this PR to run CI on all python versions.

2024-07-10 15:48 UTC, albi3ro commented
Potentially, we could move `qml.typing.TapeBatch` to `qml.tape.TapeBatch`. Then, we could use the actual class and not have circular dependencies.

2024-07-22 21:17 UTC, albi3ro commented on pennylane/transforms/__init__.py
> +    from pennylane.tape import QuantumTape, TapeBatch
```suggestion
    from pennylane.tape import QuantumTape, QuantumTapeBatch
```
and associated changes.

2024-07-22 21:17 UTC, albi3ro commented on pennylane/transforms/__init__.py
> +    def remove_rx(tape: QuantumTape) -> tuple[TapeBatch, PostprocessingFn]:
```suggestion
    def remove_rx(tape: QuantumTape) -> tuple[QuantumTapeBatch, PostprocessingFn]:
```

2024-07-22 21:18 UTC, albi3ro commented on pennylane/transforms/__init__.py
> +    from pennylane.tape import QuantumTape, TapeBatch
```suggestion
    from pennylane.tape import QuantumTape, QuantumTapeBatch
```

2024-07-22 21:18 UTC, albi3ro commented on pennylane/transforms/__init__.py
> +    def sum_circuit_and_adjoint(tape: QuantumTape) -> tuple[TapeBatch, PostprocessingFn]:
```suggestion
    def sum_circuit_and_adjoint(tape: QuantumTape) -> tuple[QuantumTapeBatch, PostprocessingFn]:
```

2024-07-23 15:10 UTC, albi3ro approved these changes
🎉 Excellent work :)

2024-07-23 18:33 UTC, EmilianoG-byte approved these changes
Looks good to me, great work ㊗️!

Just one not blocking question: did you add `Optional` to all the arguments that are actually optional? Or is this something that we will add later on when we start using type checkers?

2024-07-23 18:42 UTC, Shiro-Raven commented
> Looks good to me, great work ㊗️!
> 
> Just one not blocking question: did you add `Optional` to all the arguments that are actually optional? Or is this something that we will add later on when we start using type checkers?

Yeah that's out of scope I would say

2024-07-23 21:59 UTC, merged