Fix split_non_commuting bug for Hamiltonians with identity term
PennyLaneAI/pennylane pull request #6022
Opened 2024-07-22 15:52 UTC by austingmhuang

**Context:**
Described in https://github.com/PennyLaneAI/pennylane/issues/5924, but to summarize, `split_non_commuting` does not handle Identity terms with non-trainable coefficients well, leading to an unexpected `NonDifferentiableError`.

**Description of the Change:**
Since the coefficients of Identity terms (also known as `offset`) is assumed to be a float given the type-hinting of `_sum_terms()`, we coerce the type of offset to be a float.

**Benefits:**
Fixes https://github.com/PennyLaneAI/pennylane/issues/5924

**Possible Drawbacks:**
We may not want to coerce the type of offset to be a `float`. 
Alternatively, we may want to relax the type-hinting of `offset` to include `tensor`. 
Alternatively, we can create a tighter conditional statement that checks firstly if the interface is autograd, and, if `requires_grad` is an attribute for offset, sets `requires_grad` to `True`. 

**Related GitHub Issues:**
[sc-67508]

2024-07-24 19:03 UTC, soranjh approved these changes
Thanks @austingmhuang for fixing this. 

[optional] You might update the type hinting issue in this PR as well.

2024-08-12 14:16 UTC, albi3ro commented on pennylane/transforms/split_non_commuting.py
> +    offsets: list[Union[float, TensorLike]],
```suggestion
    offsets: list[TensorLike],
```
float is included in the definition of `TensorLike`.

2024-08-12 14:16 UTC, albi3ro commented on pennylane/transforms/split_non_commuting.py
> +        single_term_obs_mps (Dict[MeasurementProcess, Tuple[List[int], List[Union[float, TensorLike]]]]): A dictionary
```suggestion
        single_term_obs_mps (Dict[MeasurementProcess, Tuple[List[int], List[TensorLike]]]): A dictionary
```

2024-08-12 14:21 UTC, albi3ro requested changes
Even if this fixes this particular problem, it will probably cause worse problems that will be extremely difficult to track down. Making something trainable can force us to do a lot more work later. Work the user explicitly didn't want.  If someone marked something as trainable, but for some reason it starts being trainable, that could be really difficult to track down.

I'd prefer to find a different solution instead.

2024-08-12 22:19 UTC, austingmhuang commented
> Even if this fixes this particular problem, it will probably cause worse problems that will be extremely difficult to track down. Making something trainable can force us to do a lot more work later. Work the user explicitly didn't want. If someone marked something as trainable, but for some reason it starts being trainable, that could be really difficult to track down.
> 
> I'd prefer to find a different solution instead.

I'm not sure what the best fix for this particular problem is actually. 

How about this? We could add an additional check to see if the coeffs are trainable. Since the offset is just the coeff for the identity term, we can assume that the differentiability of the offset based on the differentiability of the coeffs. If coeff is trainable -> set `requires_grad` to `True` -- otherwise we set it to `False`.

2024-08-13 20:30 UTC, astralcai commented
> Even if this fixes this particular problem, it will probably cause worse problems that will be extremely difficult to track down. Making something trainable can force us to do a lot more work later. Work the user explicitly didn't want. If someone marked something as trainable, but for some reason it starts being trainable, that could be really difficult to track down.
> 
> I'd prefer to find a different solution instead.

Unfortunately, after some investigation, it turned out that the reason why [this solution](https://github.com/PennyLaneAI/pennylane/pull/5945) worked was that it also caused things to become trainable, specifically via [this line](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/numpy/tensor.py#L170).

2024-08-13 20:41 UTC, austingmhuang commented
> Unfortunately, after some investigation, it turned out that the reason why [this solution](https://github.com/PennyLaneAI/pennylane/pull/5945) worked was that it also caused things to become trainable, specifically via [this line](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/numpy/tensor.py#L170).

Is there a way to fix these two bugs without causing things to become trainable?

2024-08-13 20:54 UTC, soranjh commented
> Since the offset is just the coeff for the identity term, we can assume the differentiability of the offset based on the differentiability of the coeffs. If coeff is trainable -> set requires_grad to True -- otherwise we set it to False.

This seems like a reasonable solution.

2024-08-13 21:05 UTC, astralcai commented
I think there's a deeper issue here. The error is always raised from [here](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/numpy/tensor.py#L308), which forbids turning an untrainable tensor to an `ArrayBox`. When the code executes to [this line](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/transforms/split_non_commuting.py#L719), since there are other things in the circuit that are trainable, `sum_dot_products` is an `ArrayBox`, so executing `+` takes us [here](https://github.com/HIPS/autograd/blob/master/autograd/tracer.py#L31). This is a recursive function that takes values out of an `ArrayBox` [here](https://github.com/HIPS/autograd/blob/master/autograd/tracer.py#L37), performs the underlying operation [here](https://github.com/HIPS/autograd/blob/master/autograd/tracer.py#L44), and repackages the result into an `ArrayBox` [here](https://github.com/HIPS/autograd/blob/master/autograd/tracer.py#L46).

The issue is, when performing the underlying operation, we have on one hand the value that was taken out of the `ArrayBox` (which is now just a regular value), and on the other hand a tensor that was explicitly marked untrainable, the result is also an untrainable tensor. When autograd tries to repackage this result into an `ArrayBox`, it dispatches to [this function](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/numpy/tensor.py#L290), which now complains that it doesn't allow an untrainable tensor to be converted into an `ArrayBox`.

2024-08-13 21:11 UTC, astralcai commented
> > Since the offset is just the coeff for the identity term, we can assume the differentiability of the offset based on the differentiability of the coeffs. If coeff is trainable -> set requires_grad to True -- otherwise we set it to False.
> 
> This seems like a reasonable solution to me. cc @albi3ro @astralcai

Maybe instead of assuming that all coeffs have the same trainability, we look at whether `summed_dot_products` is trainable, so something like:

```python
...
def _sum_terms(res: ResultBatch, coeffs: list[float], offset: float, shape: tuple) -> Result:
    ...
    summed_dot_products = qml.math.sum(qml.math.stack(dot_products), axis=0)
    if qml.math.get_interface(offset) == "autograd" and qml.math.requires_grad(summed_dot_products):
        offset = qml.math.array(offset)
    return summed_dot_products + offset
```

2024-08-28 19:08 UTC, merged