Add is_leaf argument to pytrees\pytrees.py with test at tests\pytrees\test_pytrees.py, fixes #6083
PennyLaneAI/pennylane pull request #6107
Opened 2024-08-16 10:32 UTC by tonmoy-b

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**
Add is_leaf argument to pytrees\pytrees.py with test at tests\pytrees\test_pytrees.py
fixes #6083 
**Description of the Change:**
Added is_leaf argument to the function pytrees\pytrees.py. Should this argument evaluate to True then no fufther flattening will be done. 
Added test to tests\pytrees\test_pytrees.py, with function test_flatten_is_leaf() having two test cases.
Added changelog with file \doc\releases\changelog-0.38.0.md

**Benefits:**
argument added to the function flatten which acts as a control mechanism to designate a node as leaf node even if that node could be further flattened, e.g., the node is a tuple.
**Possible Drawbacks:**

**Related GitHub Issues:**
Fixes #6083

2024-08-16 13:52 UTC, albi3ro commented on pennylane/pytrees/pytrees.py
> +    obj: Any, is_leaf: Callable[[Any], bool] | None = None
```suggestion
    obj: Any, is_leaf: Optional[Callable[[Any], bool]] = None
```
Note that we still support Python 3.9, at least for the near future.  The `| None` syntax is only available in Python 3.10+.

2024-08-16 13:59 UTC, albi3ro reviewed
Thanks for opening this PR :) Looks great other than the 3.10+ typing hinting syntax.

2024-08-16 14:15 UTC, mudit2812 commented on pennylane/pytrees/pytrees.py
> +        the current object.
```suggestion
        is_leaf (Callable[[Any], bool] | None = None): an optionally specified
            function that will be called at each flattening step. It should return
            a boolean, with ``True`` stopping the traversal and the whole subtree being
            treated as a leaf, and ``False`` indicating the flattening should traverse
            the current object.
```

2024-08-16 14:16 UTC, mudit2812 commented on pennylane/pytrees/pytrees.py
> +        the current object.
The indentation is needed for the documentation to render properly.

2024-08-16 14:23 UTC, tonmoy-b commented
hi @albi3ro and @mudit2812, thanks for the review and suggestions. I have accepted the suggested changes. Do let me know if it would be nice for me to look work on any other contributions, I'd love to get more familiar with the code.

2024-08-16 14:51 UTC, mudit2812 requested changes
Thanks for opening this PR @tonmoy-b ! The implementation looks great. I left some suggestions for the changelog. Do you mind also adding a couple of more tests:
* A test to verify that the pytree structure returned by `flatten` is correct when given an `is_leaf` argument.
* A test to verify that flattening and then unflattening the same pytree will be equivalent to the original object when `flatten` is given an `is_leaf` argument.

Other than the above comments, the PR is in great shape and I'm happy to approve once the above comments are resolved 🎉

2024-08-16 14:51 UTC, mudit2812 commented on doc/releases/changelog-dev.md
> +* Added `is_leaf` parameter to function `flatten` in `pytrees.pytrees.py`. This is to allow node flattening to be stopped for any node where the `is_leaf` Optional argument evaluates to being true.
```suggestion
* Added `is_leaf` parameter to function `flatten` in the `qml.pytrees` module. This is to allow node flattening to be stopped for any node where the `is_leaf` optional argument evaluates to being `True`.
```

2024-08-16 14:51 UTC, mudit2812 commented on doc/releases/changelog-dev.md
> +  [(#6083)](https://github.com/PennyLaneAI/pennylane/issues/6083)
The link should be to the PR, not to the issue 😄 

```suggestion
  [(#6107)](https://github.com/PennyLaneAI/pennylane/issues/6107)
```

2024-08-16 14:51 UTC, mudit2812 commented on doc/releases/changelog-dev.md
> +Tonmoy T. Bhattacharya,
```suggestion
Tonmoy T. Bhattacharya,
Gabriel Bottrill,
```

2024-08-16 19:34 UTC, albi3ro approved these changes
👍 Thanks for this PR :)

2024-08-16 23:20 UTC, Alex-Preciado commented
Thank you so much for this PR @tonmoy-b 🚀 !! We will continue with the review next week. Have a great weekend!!

2024-08-19 13:37 UTC, tonmoy-b commented
> Thanks for opening this PR @tonmoy-b ! The implementation looks great. I left some suggestions for the changelog. Do you mind also adding a couple of more tests:
> 
> * A test to verify that the pytree structure returned by `flatten` is correct when given an `is_leaf` argument.
> * A test to verify that flattening and then unflattening the same pytree will be equivalent to the original object when `flatten` is given an `is_leaf` argument.
> 
> Other than the above comments, the PR is in great shape and I'm happy to approve once the above comments are resolved 🎉

Hi @mudit2812, @albi3ro  @Alex-Preciado , 

      I have added the mentioned tests into tests\pytrees\test_pytrees.py, as three functions (test_flatten_is_leaf, test_unflatten_is_leaf, test_unflatten_for_structure_is_leaf), kindly take a look. 

Regards

2024-08-20 14:03 UTC, mudit2812 approved these changes
Thanks for adding the suggested tests! Very happy to get this in 😄

2024-08-21 13:32 UTC, merged

2024-08-21 17:29 UTC, Alex-Preciado commented
Thank you so much for this contribution @tonmoy-b !! 🚀

2024-08-21 17:43 UTC, tonmoy-b commented
> Thank you so much for this contribution @tonmoy-b !! 🚀 

Thanks Alex, it was my pleasure and I hope to make more contributions to Pennylane going forward.