Remove default qubit jax
PennyLaneAI/pennylane pull request #6209
Opened 2024-09-04 12:45 UTC by albi3ro

[sc-72785]

2024-09-10 18:17 UTC, mudit2812 requested changes
Looks great, just one (very repetitive, sorry) comment about test parametrization. Otherwise happy to approve.

Let me know if you think it makes sense to leave in the test parametrization in case we want to include any future devices. However, the comment about not needing to conditionally set test function variables based on device name should be addressed regardless.

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/core/test_hadamard_gradient.py
> -    @pytest.mark.parametrize("dev_name", ["default.qubit", "default.qubit.jax"])
We don't need to parametrize this test anymore. We can also remove `execute_fn` from the body of the test.

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/core/test_jvp.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same comment as above here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/core/test_pulse_gradient.py
> +@pytest.mark.parametrize("dev_name", ["default.qubit"])
Same comment about removing the parametrization and any test function variables conditionally set based on device name.

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/core/test_pulse_odegen.py
> +@pytest.mark.parametrize("dev_name", ["default.qubit"])
Same comment here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/core/test_vjp.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/finite_diff/test_finite_difference.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/finite_diff/test_finite_difference_shot_vec.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/finite_diff/test_spsa_gradient.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/finite_diff/test_spsa_gradient_shot_vec.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/parameter_shift/test_parameter_shift.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 18:17 UTC, mudit2812 commented on tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py
> +    @pytest.mark.parametrize("dev_name", ["default.qubit"])
Same here

2024-09-10 19:19 UTC, astralcai approved these changes

2024-09-11 19:00 UTC, mudit2812 approved these changes
Looks good! Sorry for the tedium 😅

2024-09-12 14:06 UTC, merged