[WIP] Resource operators for multi qubit operations
PennyLaneAI/pennylane pull request #6538
Opened 2024-11-06 16:26 UTC by willjmax

[sc-76761]

2024-12-02 19:47 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/__init__.py
> +    ~ResourcePSWAP
Missing `ResourcePauliRot`

2024-12-02 19:48 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/parametric_ops_multi_qubit.py
> +    r"""Resource class for the MultiRZ gate.
Missing reference for the resources method.

2024-12-02 20:48 UTC, Jaybsoni reviewed
Just a few comments to wrap up this PR: 

1. The "Resources" section for each of the operation should at least have enough information that a user can know what the expected resources are without having to run the code. In most cases we should have a paper with either the resource decomposition or a numeric expression for the cost. In the case that the gate is very fundamental, you should list out the resources or circuit diagram (see the docs for `ResourceToffoli` as an example). 
2. Regarding the QChem ops tests. Even though the implementation is still TODO, you should still test that the resources raise a NotImplemented error and that the other methods are as expected. In general, if a feature is TODO, we either don't add any code for it (just the comment) or if we add code that's empty, we make sure to test it produces empty results. 

3. Missing changelog entry. See my PRs for how to add a changelog entry. 

Once those are addressed and the docs build I am happy to approve this 👍🏼 Thanks

2024-12-02 20:48 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/parametric_ops_multi_qubit.py
> +        multi_rz = re.ResourceMultiRZ.resource_rep(active_wires, **kwargs)
Actually, I would suggest going straight to CNOT and 1 Z here. No need to go through the MultiRZ. This is one of those cases where we will get a significant performance boost for doing a single step simplification without losing much for generality.

2024-12-02 20:48 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/qchem_ops.py
> +        """TODO: implement in resource_symbolic_ops branch"""
What is required here?

2024-12-02 20:48 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/qchem_ops.py
> +        """See https://arxiv.org/abs/2104.05695"""
Link this above.

2024-12-02 20:48 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/qchem_ops.py
> +        """TODO: implement in resource_symbolic_op branch"""
What's missing?

2024-12-03 19:27 UTC, Jaybsoni requested changes
Some suggestions about the docstrings and one more efficient resources method.

2024-12-03 19:27 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/parametric_ops_multi_qubit.py
> +        an illustration.
```suggestion
    Resources:
        The resources come from Section VIII (figures 3, 4) of `The Bravyi-Kitaev transformation for 
        quantum computation of electronic structure <https://arxiv.org/pdf/1208.5986>`_ paper, in 
        combination with the following identity:

        .. math::

            \begin{align}
                \hat{X} &= \hat{H} \cdot \hat{Z} \cdot \hat{H}, \\
                \hat{Y} &= \hat{S} \cdot \hat{H} \cdot \hat{Z} \cdot \hat{H} \cdot \hat{S}^{\dagger}.
            \end{align}

        Specifically, the resources are given by one :code:`RZ` gate and a cascade of :math:`2 * (n - 1)`
        :code:`CNOT` gates where :math:`n` is the number of qubits the gate acts on. Additionally, for 
        each :code:`X` gate in the Pauli word we conjugate by a :code:`Hadamard` gate, and for each
        :code:`Y` gate in the Pauli word we conjugate by :code:`Hadamard` and :code:`S` gates.

```

2024-12-03 19:27 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/ops/qubit/parametric_ops_multi_qubit.py
> +        The circuit implementing this transformation is given by
```suggestion
        The circuit implementing this transformation is given by:
```

2024-12-03 20:45 UTC, Jaybsoni approved these changes
Looks good to me 👍🏼

2024-12-03 21:37 UTC, soranjh approved these changes

2024-12-03 22:22 UTC, merged