GQSP template and angle solver
PennyLaneAI/pennylane pull request #6565
Opened 2024-11-11 15:17 UTC by KetpuntoG

This PR introduces the [Generalized QSP](https://arxiv.org/abs/2308.01501) template and some functionality to calculate the desire polynomials.

[sc-76734]

2024-11-26 11:02 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +        function :func:`~.math.poly_to_angles` by choosing the routine ``"GQSP"``.
```suggestion
        :func:`~.math.poly_to_angles` can be used to calculate the angles given a polynomial ``poly`` with ``routine="GQSP"``.
```

2024-11-26 11:03 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +        @qml.prod # transforms the qfunc into an Operator
Nice! 🧑‍🍳

2024-11-26 11:03 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +
```suggestion
```

2024-11-26 11:03 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +
```suggestion
```

2024-11-26 11:04 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +        for theta, phi, lam in zip(thetas[1:], phis[1:], lambds[1:]):
Prefer using `lamb` instead of `lam`

2024-12-03 05:47 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +    qubit, a polynomial transformation of the unitary.
```suggestion
    qubit, a polynomial transformation of the unitary as shown below:
```

2024-12-03 05:50 UTC, obliviateandsurrender reviewed
Removing my request changes, so not to be a blocker.

2024-12-03 05:50 UTC, obliviateandsurrender commented on pennylane/templates/subroutines/gqsp.py
> +    qubit, a polynomial transformation of the unitary.
```suggestion
    qubit, a polynomial transformation of the unitary as shown below:
```

2024-12-03 05:51 UTC, obliviateandsurrender approved these changes

2024-12-03 22:33 UTC, soranjh requested changes
Thanks @KetpuntoG, addes some small comments. Looks good overall.

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +# Copyright 2018-2023 Xanadu Quantum Technologies Inc.
```suggestion
# Copyright 2024 Xanadu Quantum Technologies Inc.
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +    Implements the generalized quantum signal processing `(GQSP) <https://arxiv.org/abs/2308.01501>`__ circuit.
```suggestion
    Implements the generalized quantum signal processing (GQSP) circuit.
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +    qubit, a polynomial transformation of the unitary as shown below:
```suggestion
    This operation encodes a polynomial transformation of an input unitary operator following the algorithm 
    described in `arXiv:2308.01501 <https://arxiv.org/abs/2308.01501>`__ as:
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +
```suggestion
    The implementation requires one auxiliary qubit.
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +            operator.
```suggestion
        unitary (Operator): the operator to be encoded by the GQSP circuit
        angles (tensor[float]): array of angles defining the polynomial transformation. The shape of the array must be `(3, d+1)`, where `d` is the degree of the polynomial.
        control (Union[Wires, int, str]): control qubit used to encode the polynomial transformation
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +        unitary (Operator): The unitary operator to be applied in the generalized quantum signal processing (GQSP) circuit.
Is the name "unitary" consistent with the PRD?

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +        :func:`~.poly_to_angles` can be used to calculate the angles given a polynomial ``poly`` with ``routine="GQSP"``.
```suggestion
       The  :func:`~.poly_to_angles` function can be used to calculate the angles for a given polynomial.
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +        angles = qml.math.poly_to_angles(poly, "GQSP")
```suggestion
        angles = qml.poly_to_angles(poly, "GQSP")
```

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/qsvt.py
> +        # Matrix definition of U3 gate chosen in the GQSP paper
Please site the paper properly. The future developer will be confused about what "GQSP paper" means.

Also, it should be a private function and be outside of this function, unless something blocks that.

2024-12-03 22:33 UTC, soranjh commented on pennylane/templates/subroutines/qsvt.py
> +    # Algorithm 1 in [arXiv:2308.01501]
```suggestion
    # From Algorithm 1 in [arXiv:2308.01501]
```

2024-12-03 22:33 UTC, soranjh commented on tests/templates/test_subroutines/test_gqsp.py
> +# Copyright 2018-2023 Xanadu Quantum Technologies Inc.
```suggestion
# Copyright 2024 Xanadu Quantum Technologies Inc.
```

2024-12-03 22:33 UTC, soranjh commented on tests/templates/test_subroutines/test_gqsp.py
> +        """Test that poly_to_angles and GQSP produce the correct solution"""
[optional] better to have another separate test that only checks GQSP accuracy with a set of given angles.

The current test, does two separate tests at the same time: GQSP and  poly_to_angles.

2024-12-04 22:50 UTC, soranjh commented on tests/templates/test_subroutines/test_gqsp.py
> +        """Test that poly_to_angles and GQSP produce the correct solution"""
You can leave this test. My suggestion is to add an extra test that does not call poly_to_angles, instead uses angles computed with it (or another reference).

2024-12-06 14:55 UTC, soranjh approved these changes
Good to go :shipit:

2024-12-06 14:55 UTC, soranjh commented on pennylane/templates/subroutines/gqsp.py
> +        # P(x) = -0.1 + 0.2j x + 0.3 x^2
```suggestion
        # P(x) = 0.1 + 0.2j x + 0.3 x^2
```

2024-12-06 15:33 UTC, merged