Resource operators needed for Shor's algorithm
PennyLaneAI/pennylane pull request #6638
Opened 2024-11-26 15:31 UTC by willjmax

This PR contains ResourceOperator implementations for the ModExp, PhaseAdder, Multiplier, and ControlledSequence templates.

2024-12-05 19:45 UTC, Jaybsoni commented
[sc-79011]

2025-02-10 23:07 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/__init__.py
> +    ResourcePhaseAdder,
```suggestion
```

2025-03-18 04:48 UTC, Jaybsoni requested changes
A bunch of things to fix, I'll provide more comments as I review it further.

2025-03-18 04:49 UTC, Jaybsoni commented
Also now that we have more detailed documentation, could you also update the docs of these templates, I can help out anywhere things are unclear!

2025-03-18 19:25 UTC, austingmhuang commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +        gate_types[phase_shift] = num_wires * 2
Ah, I misread this as `if qml.math.is_abstract()`, so I thought that decomposition was specifically for jax tracer objects rather than the other way around.

2025-03-20 20:26 UTC, Jaybsoni reviewed
Some more comments

2025-03-20 20:26 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +        assert num_swap_wires + num_select_wires <= num_control_wires
Whoops, don't need this
```suggestion
```

2025-03-20 20:26 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +            The resources are taken from the decomposition of ``qml.AmplitudeAmplification`` class.
I believe this should link it.
```suggestion
            The resources are taken from the decomposition of :class:`qml.AmplitudeAmplification` class.
```

2025-03-20 21:46 UTC, soranjh commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +            `Fomichev et al. (2024) <https://journals.aps.org/prxquantum/pdf/10.1103/PRXQuantum.5.040339>`_.
You can remove the reference to Fomichev et al. and just cite the PL class.

2025-03-21 17:47 UTC, soranjh approved these changes

2025-03-21 21:38 UTC, Jaybsoni reviewed
Final set of comments. Looks good to go after this

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    """Resource class for StatePrep.
See ResourceQFT as an example. Just missing a `.. seealso ` and a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    """Resource class for the MottonenStatePreparation template.
See ResourceQFT as an example. Just missing a .. seealso  and a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    """Resource class for the `:class:~.Superposition` template.
See ResourceQFT as an example. Just missing a .. seealso  and a simple example
```suggestion
    """Resource class for the Superposition template.
```

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +        -   If the number of basis states provided spans the set of all basis states,
Does this render well?

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +        )
Since its just one control, we should use `ResourceControlledPhaseShift`

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    r"""Resource class for the BasisState template.
See ResourceQFT as an example. Just missing a .. seealso  and a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +    """Resource class for the :class:`~.ControlledSequence` template.
See ResourceQFT as an example. Just missing a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +    r"""Resource class for the :class:`~.PhaseAdder` template.
See ResourceQFT as an example. Just missing a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +    """Resource class for the :class:`~.Multiplier` template.
See ResourceQFT as an example. Just missing a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +    r"""Resource class for the :class:`~.ModExp` template.
See ResourceQFT as an example. Just missing a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +    """Resource class for the QROM template.
See ResourceQFT as an example. Just missing a .. seealso  and a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +    r"""Resource class for the AmplitudeAmplification template.
See ResourceQFT as an example. Just missing a .. seealso  and a simple example

2025-03-21 21:38 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +        * fixed_point (bool): whether to use the fixed-point amplitude amplification algorithm
Need to have type since we are passing a reference to the class not an instance of the class. 
```suggestion
        * U_op (Type[~.ResourceOperator]): the class of the operator that prepares the state :math:`|\Psi\rangle`
        * U_params (dict): the parameters for the U operator
        * O_op (Type[~.ResourceOperator]): the class of the oracle that flips the sign of the state :math:`|\phi\rangle` and does nothing to the state :math:`|\phi^{\perp}\rangle`
        * O_params (dict): the parameters for the O operator
        * iters (int): the number of iterations of the amplitude amplification subroutine
        * num_ref_wires (int): the number of wires used for the reflection
        * fixed_point (bool): whether to use the fixed-point amplitude amplification algorithm
```

2025-03-21 22:15 UTC, austingmhuang commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +        -   If the number of basis states provided spans the set of all basis states,
Looks fine to me

2025-03-21 22:23 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    >>> re.ResourceSuperposition.resources(3, 3, 3)
```suggestion
    >>> re.ResourceSuperposition.resources(num_stateprep_wires=3, num_basis_states=3, size_basis_state=3)
```

2025-03-21 22:24 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    >>> re.ResourceBasisState.resources(6)
```suggestion
    >>> re.ResourceBasisState.resources(num_bit_flips = 6)
```

2025-03-24 14:14 UTC, Jaybsoni reviewed
Looks good to go, just a few comments. Also I think it's best if we do include the name of the kwargs in the simple examples for each operation. Being clear is better in that case is better.

2025-03-24 14:14 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    .. seealso:: `:class:~.StatePrep`
Didn't render properly 
```suggestion
    .. seealso:: :class:`~.StatePrep`
```

2025-03-24 14:14 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    .. seealso:: `:class:~.MottonenStatePreperation`
same here

2025-03-24 14:14 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    .. seealso:: `:class:~.Superposition`
Same here

2025-03-24 14:14 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +    .. seealso:: `:class:~.BasisState`
same here

2025-03-24 14:14 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/subroutines.py
> +        * mod (int): the module for performing the exponentiation
```suggestion
        * mod (int): the modulo for performing the modular exponentiation
```

2025-03-24 14:35 UTC, austingmhuang commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +        * num_wires (int): the number of wires that StatePrep acts on
This is consistent with other RE docs (see QPE for example). We need the * or else sphinx will not render/build this as a list correctly.

2025-03-24 16:21 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +                * num_wires (int): the number of wires that StatePrep acts on
```suggestion
                * num_wires (int): the number of wires that the operation acts on
```

2025-03-24 16:22 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +            num_wires (int): the number of wires that StatePrep acts on
```suggestion
            num_wires (int): the number of wires that the operation acts on
```

2025-03-24 16:22 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +        * num_wires(int): the number of wires that StatePrep acts on
```suggestion
        * num_wires(int): the number of wires that the operation acts on
```

2025-03-24 16:22 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +            num_wires(int): the number of wires that StatePrep acts on
```suggestion
            num_wires(int): the number of wires that the operation acts on
```

2025-03-24 16:23 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +                * num_wires(int): the number of wires that StatePrep acts on
```suggestion
                * num_wires(int): the number of wires that the operation acts on
```

2025-03-24 16:23 UTC, Jaybsoni commented on pennylane/labs/resource_estimation/templates/stateprep.py
> +            num_wires(int): the number of wires that StatePrep acts on
```suggestion
            num_wires(int): the number of wires that the operation acts on
```

2025-03-25 13:58 UTC, merged