AngleEmbedding fewer features than qubits temp func
PennyLaneAI/pennylane pull request #881
Opened 2020-10-30 13:18 UTC by antalszava

Adds a function that wraps `broadcast` to disable the shape check. This allows fewer features as qubits to be used with `AngleEmbedding`.

2020-11-02 07:49 UTC, mariaschuld requested changes
I think I understand the issue only now fully. Sorry if that caused unnecessary work

Basically there is a missing step in `AngleEmbedding`: If the number of wires is greater than the number of inputs, we only send `wires[:len(features)]` into the broadcast function. Your test is a great addition either way, there should have been a test case for this! 

Note that `len(features)` is just pseudocode which will fail in tape mode, it is better (for now, but we need to improve on that) to get this value like this:

```
 shp = check_shape(
    ...
    )
   ...
   wires = wires[:shp[0]]
``` 

I checked and your test seems to pass with this and using the normal `broadcast` function. Let me know if I must push the changes, but should be just a few lines.

2020-11-02 17:31 UTC, mariaschuld reviewed
Maybe you should review now rather than me @antalszava :)

2020-11-03 13:05 UTC, mariaschuld approved these changes

2020-11-03 18:36 UTC, antalszava commented
@mariaschuld looks good to me! :100: Thanks for the update here :)

2020-11-04 16:37 UTC, merged