Fix decomposition for inverse S and T gates
PennyLaneAI/pennylane pull request #956
Opened 2020-12-08 08:12 UTC by josh146

**Context:**

Two bugs were recently discovered in #955.

* The decomposition for the S and T gates were not taking into account whether the gate has been inverted. This did not affect any other operations, since in all either cases either (a) the gate is its own inverse (so no action needed, e.g., X), or (b) the gate was inverted by negating the parameters (done automatically by the `Operation` class, e.g., PhaseShift).

* The tape QNode was decomposing gates based on the contents of `device.operations`. Instead, it should have been using `device.supports_operation()`, which has additional logic to deal with inverses.

**Description of the Change:**

* `qml.S.decomposition` and `qml.T.decomposition` now properly return the correct decomposition if the gate has been inverted.

* Adds tests to make sure this logic works.

**Benefits:**

* Devices that don't natively support `qml.S.inv()` and `qml.T.inv()` are now provided with the correct decomposition.

* In tape mode, devices that *do* support `qml.S.inv()` and `qml.T.inv()` do not have these operations decomposed.

**Possible Drawbacks:** n/a

**Related GitHub Issues:** Fixes #995

2020-12-08 18:18 UTC, glassnotes approved these changes
Thanks for taking care of this so quickly @josh146 !

2020-12-08 18:18 UTC, glassnotes commented on pennylane/ops/qubit.py
> +            return [PhaseShift(-np.pi / 2, wires=wires)]
:100:

2020-12-08 19:10 UTC, antalszava requested changes
Hi @josh146, good catch with the decomposition! I'm a bit still hesitant with non-tape mode, however.

Would the inverse of the decomposition not be accounted for in the QNode? :thinking: 
https://github.com/PennyLaneAI/pennylane/blob/c0d269e5f1eba2f9d033bd9b6a79c10a11f4228a/pennylane/qnodes/base.py#L100

When decomposing the inverse of the `S` or `T` gates, by taking the inverse of the decomposition on the operation level, it seems that we end up taking the inverse twice overall (and simply applying `S` or `T` eventually):
```python
import pennylane as qml

qml.disable_tape()
dev = qml.device('default.qubit.autograd', wires=1)

if "S" in dev.operations:
    dev.operations.remove("S")

@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=0)
    qml.S(wires=0).inv()
    return qml.expval(qml.PauliZ(0))

circuit()
dev.state
```
```
tensor([7.07106781e-01+0.j        , 4.32978028e-17+0.70710678j], requires_grad=True)
```
The same example of using the decomposition in tape mode:
```
tensor([7.07106781e-01+0.j        , 4.32978028e-17-0.70710678j], requires_grad=True)
```
Perhaps adding such examples (or similar) as higher-level integration tests could help here.

2020-12-09 08:17 UTC, josh146 commented
@antalszava you're entirely right, thank you for noticing that! Considering your comment, I've done the following:

* Removed the inverse branches in the S and T decompositions,

* Modified `Operation.expand()` so that if the original operation is inverted, so is the final decomposition,

* Added a high-level integration test to check all combinations of tape/non-tape mode, and decompositions/non-decompositions.

2020-12-09 14:52 UTC, antalszava approved these changes
Looks good to me! :1st_place_medal: Great fix :slightly_smiling_face: Was wondering about a test case for `T` too, probably the `S` test case sort of covers the specific case though (as `T` and `S` are very similar gates and the operations themselves are tested separately).

2020-12-09 14:52 UTC, antalszava commented on tests/devices/test_default_qubit.py
> +        monkeypatch.setattr(dev, "operations", patched_operations)
:100:

2020-12-09 16:23 UTC, merged